In [1]:
import pandas as pd
import numpy as np
import torch

In [2]:
class Feedforward(torch.nn.Module):
        def __init__(self, input_size, hidden_size, dropout):
            super(Feedforward, self).__init__()
            self.input_size = input_size
            self.hidden_size  = hidden_size
            self.fc_in = torch.nn.Linear(self.input_size, self.hidden_size)
            self.fc1 = torch.nn.Linear(self.hidden_size, self.hidden_size)
            self.fc2 = torch.nn.Linear(self.hidden_size, self.hidden_size)
            self.relu = torch.nn.ReLU()
            #self.relu = torch.nn.LeakyReLU(0.1)
            self.fc_out = torch.nn.Linear(self.hidden_size, 1)
            self.sigmoid = torch.nn.Sigmoid()
            self.dropout = torch.nn.Dropout(dropout)
            
        def forward(self, x):
            x = self.fc_in(x)
            x = self.dropout(x)
            x = self.relu(x)
            x = self.fc1(x)
            x = self.dropout(x)
            x = self.relu(x)
            x = self.fc2(x)
            x = self.dropout(x)
            x = self.relu(x)
            output = self.fc_out(x)
            output = self.sigmoid(output)
            return output

In [3]:
data = pd.read_csv('/Users/nkerstingadxnet.com/Documents/Higgs/orig/atlas-higgs-challenge-2014-v2.csv')
data['Binary_Label'] = data['Label'].map({'s':1,'b':0})

In [4]:
nonphi_columns = [c for c in data.columns if "phi" in c]
for col in nonphi_columns:
    data.drop(col, axis=1, inplace=True)
data.head()

,EventId,DER_mass_MMC,DER_mass_transverse_met_lep,DER_mass_vis,DER_pt_h,DER_deltaeta_jet_jet,DER_mass_jet_jet,DER_prodeta_jet_jet,DER_deltar_tau_lep,DER_pt_tot,...,PRI_jet_leading_pt,PRI_jet_leading_eta,PRI_jet_subleading_pt,PRI_jet_subleading_eta,PRI_jet_all_pt,Weight,Label,KaggleSet,KaggleWeight,Binary_Label
0,100000,138.470,51.655,97.827,27.980,0.91,124.711,2.666,3.064,41.928,...,67.435,2.150,46.062,1.24,113.497,0.000814,s,t,0.002653,1
1,100001,160.937,68.768,103.235,48.146,-999.00,-999.000,-999.000,3.473,2.078,...,46.226,0.725,-999.000,-999.00,46.226,0.681042,b,t,2.233584,0
2,100002,-999.000,162.172,125.953,35.635,-999.00,-999.000,-999.000,3.148,9.336,...,44.251,2.053,-999.000,-999.00,44.251,0.715742,b,t,2.347389,0
3,100003,143.905,81.417,80.943,0.414,-999.00,-999.000,-999.000,3.310,0.414,...,-999.000,-999.000,-999.000,-999.00,-0.000,1.660654,b,t,5.446378,0
4,100004,175.864,16.915,134.805,16.405,-999.00,-999.000,-999.000,3.891,16.405,...,-999.000,-999.000,-999.000,-999.00,0.000,1.904263,b,t,6.245333,0

In [5]:
# now replace all the '-999' values with NULL so we can properly handle them
#nulled_data = data.replace(-999.0, np.nan)
nulled_data = data.replace(-999.0, 0)
train_data = nulled_data.loc[nulled_data['KaggleSet'] == 't'].copy(deep=True)
public_test_data = nulled_data.loc[nulled_data['KaggleSet'] == 'b'].copy(deep=True)
private_test_data = nulled_data.loc[nulled_data['KaggleSet'] == 'v'].copy(deep=True)

In [6]:
orig_train_data = train_data.copy(deep=True)
orig_public_test_data = public_test_data.copy(deep=True)
orig_private_test_data = private_test_data.copy(deep=True)


# now replace the null values with column averages
train_data.drop('EventId', axis=1, inplace=True)
train_data.drop('Label', axis=1, inplace=True)
train_data.drop('Binary_Label', axis=1, inplace=True)
train_data.drop('Weight', axis=1, inplace=True)
train_data.drop('KaggleWeight', axis=1, inplace=True)
train_data.drop('KaggleSet', axis=1, inplace=True)
for col in train_data:
    train_data[col].fillna(train_data[col].mean(), inplace=True)
#train_data.isnull().sum()


public_test_data.drop('EventId', axis=1, inplace=True)
public_test_data.drop('Label', axis=1, inplace=True)
public_test_data.drop('Binary_Label', axis=1, inplace=True)
public_test_data.drop('Weight', axis=1, inplace=True)
public_test_data.drop('KaggleWeight', axis=1, inplace=True)
public_test_data.drop('KaggleSet', axis=1, inplace=True)
for col in public_test_data:
    public_test_data[col].fillna(public_test_data[col].mean(), inplace=True)
#public_test_data.isnull().sum()


private_test_data.drop('EventId', axis=1, inplace=True)
private_test_data.drop('Label', axis=1, inplace=True)
private_test_data.drop('Binary_Label', axis=1, inplace=True)
private_test_data.drop('Weight', axis=1, inplace=True)
private_test_data.drop('KaggleWeight', axis=1, inplace=True)
private_test_data.drop('KaggleSet', axis=1, inplace=True)
for col in private_test_data:
    private_test_data[col].fillna(private_test_data[col].mean(), inplace=True)
#private_test_data.isnull().sum()

In [7]:
# now let's normalize
normed_train_data = (train_data - train_data.min())/(train_data.max() - train_data.min())

normed_public_test_data = (public_test_data - public_test_data.min())/(public_test_data.max() - public_test_data.min())

normed_private_test_data = (private_test_data - private_test_data.min())/(private_test_data.max() - private_test_data.min())

In [8]:
normed_train_data.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 250000 entries, 0 to 249999
Data columns (total 24 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   DER_mass_MMC                 250000 non-null  float64
 1   DER_mass_transverse_met_lep  250000 non-null  float64
 2   DER_mass_vis                 250000 non-null  float64
 3   DER_pt_h                     250000 non-null  float64
 4   DER_deltaeta_jet_jet         250000 non-null  float64
 5   DER_mass_jet_jet             250000 non-null  float64
 6   DER_prodeta_jet_jet          250000 non-null  float64
 7   DER_deltar_tau_lep           250000 non-null  float64
 8   DER_pt_tot                   250000 non-null  float64
 9   DER_sum_pt                   250000 non-null  float64
 10  DER_pt_ratio_lep_tau         250000 non-null  float64
 11  DER_lep_eta_centrality       250000 non-null  float64
 12  PRI_tau_pt                   250000 non-null  float64
 13  PRI_tau_eta                  250000 non-null  float64
 14  PRI_lep_pt                   250000 non-null  float64
 15  PRI_lep_eta                  250000 non-null  float64
 16  PRI_met                      250000 non-null  float64
 17  PRI_met_sumet                250000 non-null  float64
 18  PRI_jet_num                  250000 non-null  float64
 19  PRI_jet_leading_pt           250000 non-null  float64
 20  PRI_jet_leading_eta          250000 non-null  float64
 21  PRI_jet_subleading_pt        250000 non-null  float64
 22  PRI_jet_subleading_eta       250000 non-null  float64
 23  PRI_jet_all_pt               250000 non-null  float64
dtypes: float64(24)
memory usage: 47.7 MB

In [9]:
train_input_data = []
for i in range(len(orig_train_data)):
   train_input_data.append([torch.tensor(normed_train_data.iloc[i], dtype=torch.float), torch.tensor(orig_train_data['Binary_Label'].iloc[i] , dtype=torch.float)])
valid_input_data = []
for i in range(len(orig_public_test_data)):
   valid_input_data.append([torch.tensor(normed_public_test_data.iloc[i], dtype=torch.float), torch.tensor(orig_public_test_data['Binary_Label'].iloc[i] , dtype=torch.float)])

In [10]:
from torch.utils.data import DataLoader

train_dataloader = DataLoader(train_input_data, batch_size=128, shuffle=True)
valid_dataloader = DataLoader(valid_input_data, batch_size=128, shuffle=True)

In [11]:
model = Feedforward(24, 600, 0.05)
criterion = torch.nn.BCELoss()
optimizer = torch.optim.SGD(model.parameters(), lr = 0.01)

In [12]:
import time
import copy
from datetime import datetime

now = datetime.now()
dt_string = now.strftime("%d%m%Y%H%M%S")
logfile = open(dt_string + ".log",'w')

start_time = time.time()
epoch = 20
maxvalcount = 5
minval_loss = np.inf
valcount = maxvalcount
best_model = model
for epoch in range(epoch):
    print("EPOCH: ", epoch)
    model.train()
    for i,batch in enumerate(train_dataloader):
        inputs, output = batch
        optimizer.zero_grad()
        # Forward pass
        y_pred = model(inputs)
        # Compute Loss
        loss = criterion(y_pred.squeeze(), output)
        if i % 100 == 0:
            logstring = 'Batch {}: train loss: {}'.format(i, loss.item())
            print(logstring)
            logfile.write(logstring + '\n')
        # Backward pass
        loss.backward()
        optimizer.step()
    # compute validation loss
    model.eval()
    with torch.set_grad_enabled(False):
        val_loss = 0
        for i,batch in enumerate(valid_dataloader):
            inputs, output = batch
            y_pred = model(inputs)
            y_pred = model(inputs)
            loss = criterion(y_pred.squeeze(), output)
            val_loss += loss
            if i % 100 == 0:
                logstring = 'Validation Batch {}: loss: {}'.format(i, loss.item())
                print(logstring)
                logfile.write(logstring + '\n')
        avg_val_loss = val_loss / len(valid_dataloader)
        valstring = f"AVERAGE BATCH VAL LOSS = {avg_val_loss}"
        print(valstring)
        logfile.write(valstring + '\n')
    if avg_val_loss < minval_loss:
        minval_loss = avg_val_loss
        best_model = copy.deepcopy(model)
        valcount = maxvalcount
    else:
        valcount -= 1
    if valcount == 0:
        endmsg = f"Validation Loss failed to decrease in {maxvalcount} epochs, exiting with best model, val loss = {minval_loss}"
        print(endmsg)
        logfile.write(endmsg + '\n')
        break

end_time = time.time()
timestring = f"Time elapsed in training: {end_time - start_time} seconds"
print(timestring)
logfile.write(timestring + '\n')

EPOCH:  0
Batch 0: train loss: 0.6917551159858704
Batch 100: train loss: 0.6666089296340942
Batch 200: train loss: 0.6316730976104736
Batch 300: train loss: 0.6139228940010071
Batch 400: train loss: 0.6790646910667419
Batch 500: train loss: 0.6557291150093079
Batch 600: train loss: 0.6449435353279114
Batch 700: train loss: 0.6652800440788269
Batch 800: train loss: 0.6344177722930908
Batch 900: train loss: 0.6423394083976746
Batch 1000: train loss: 0.6257915496826172
Batch 1100: train loss: 0.6098276972770691
Batch 1200: train loss: 0.6416054964065552
Batch 1300: train loss: 0.5883806347846985
Batch 1400: train loss: 0.6087237596511841
Batch 1500: train loss: 0.6166571974754333
Batch 1600: train loss: 0.6526719331741333
Batch 1700: train loss: 0.6648691296577454
Batch 1800: train loss: 0.60236656665802
Batch 1900: train loss: 0.6082302331924438
Validation Batch 0: loss: 0.6097041368484497
Validation Batch 100: loss: 0.5880580544471741
Validation Batch 200: loss: 0.626838207244873
Validation Batch 300: loss: 0.6059600114822388
Validation Batch 400: loss: 0.5831350088119507
Validation Batch 500: loss: 0.6400502324104309
Validation Batch 600: loss: 0.6231482028961182
Validation Batch 700: loss: 0.6406416893005371
AVERAGE BATCH VAL LOSS = 0.6178432106971741
EPOCH:  1
Batch 0: train loss: 0.6561004519462585
Batch 100: train loss: 0.6113365292549133
Batch 200: train loss: 0.6230719089508057
Batch 300: train loss: 0.6503257155418396
Batch 400: train loss: 0.6260614395141602
Batch 500: train loss: 0.6112694144248962
Batch 600: train loss: 0.606222927570343
Batch 700: train loss: 0.614468514919281
Batch 800: train loss: 0.58851557970047
Batch 900: train loss: 0.6458711624145508
Batch 1000: train loss: 0.5797632932662964
Batch 1100: train loss: 0.6108243465423584
Batch 1200: train loss: 0.63720703125
Batch 1300: train loss: 0.5775021910667419
Batch 1400: train loss: 0.6312611103057861
Batch 1500: train loss: 0.5173987746238708
Batch 1600: train loss: 0.5822007656097412
Batch 1700: train loss: 0.5976453423500061
Batch 1800: train loss: 0.6061261296272278
Batch 1900: train loss: 0.6196783781051636
Validation Batch 0: loss: 0.5874794125556946
Validation Batch 100: loss: 0.5950869917869568
Validation Batch 200: loss: 0.6041688323020935
Validation Batch 300: loss: 0.615383505821228
Validation Batch 400: loss: 0.6046741604804993
Validation Batch 500: loss: 0.5780048966407776
Validation Batch 600: loss: 0.5887119174003601
Validation Batch 700: loss: 0.6363752484321594
AVERAGE BATCH VAL LOSS = 0.6013069748878479
EPOCH:  2
Batch 0: train loss: 0.5945199728012085
Batch 100: train loss: 0.5866168737411499
Batch 200: train loss: 0.5894366502761841
Batch 300: train loss: 0.5834043025970459
Batch 400: train loss: 0.6460274457931519
Batch 500: train loss: 0.6082018613815308
Batch 600: train loss: 0.5507453680038452
Batch 700: train loss: 0.5942633748054504
Batch 800: train loss: 0.5824414491653442
Batch 900: train loss: 0.5977866649627686
Batch 1000: train loss: 0.5413471460342407
Batch 1100: train loss: 0.6099556088447571
Batch 1200: train loss: 0.6190171241760254
Batch 1300: train loss: 0.5988237857818604
Batch 1400: train loss: 0.5813422799110413
Batch 1500: train loss: 0.5497838854789734
Batch 1600: train loss: 0.5350049138069153
Batch 1700: train loss: 0.5722895860671997
Batch 1800: train loss: 0.5624129772186279
Batch 1900: train loss: 0.5794506669044495
Validation Batch 0: loss: 0.593757688999176
Validation Batch 100: loss: 0.5381419658660889
Validation Batch 200: loss: 0.579481840133667
Validation Batch 300: loss: 0.584882378578186
Validation Batch 400: loss: 0.5971269011497498
Validation Batch 500: loss: 0.5966706871986389
Validation Batch 600: loss: 0.5762595534324646
Validation Batch 700: loss: 0.5723117589950562
AVERAGE BATCH VAL LOSS = 0.5769085884094238
EPOCH:  3
Batch 0: train loss: 0.5382580161094666
Batch 100: train loss: 0.5830793380737305
Batch 200: train loss: 0.5772368907928467
Batch 300: train loss: 0.5696706175804138
Batch 400: train loss: 0.5539253354072571
Batch 500: train loss: 0.5326619148254395
Batch 600: train loss: 0.6197524666786194
Batch 700: train loss: 0.5492914319038391
Batch 800: train loss: 0.5884876847267151
Batch 900: train loss: 0.534669816493988
Batch 1000: train loss: 0.5748559236526489
Batch 1100: train loss: 0.5539807081222534
Batch 1200: train loss: 0.5341618061065674
Batch 1300: train loss: 0.49698781967163086
Batch 1400: train loss: 0.5424581170082092
Batch 1500: train loss: 0.4843299090862274
Batch 1600: train loss: 0.5014159083366394
Batch 1700: train loss: 0.5324976444244385
Batch 1800: train loss: 0.48796531558036804
Batch 1900: train loss: 0.5339885950088501
Validation Batch 0: loss: 0.5621277093887329
Validation Batch 100: loss: 0.5718414783477783
Validation Batch 200: loss: 0.5198954343795776
Validation Batch 300: loss: 0.48789089918136597
Validation Batch 400: loss: 0.5612834692001343
Validation Batch 500: loss: 0.6028106808662415
Validation Batch 600: loss: 0.5790432691574097
Validation Batch 700: loss: 0.5128461122512817
AVERAGE BATCH VAL LOSS = 0.5244830846786499
EPOCH:  4
Batch 0: train loss: 0.5564972758293152
Batch 100: train loss: 0.5288830399513245
Batch 200: train loss: 0.5612329244613647
Batch 300: train loss: 0.4776521325111389
Batch 400: train loss: 0.5038175582885742
Batch 500: train loss: 0.539821207523346
Batch 600: train loss: 0.5099413990974426
Batch 700: train loss: 0.5451584458351135
Batch 800: train loss: 0.5087479948997498
Batch 900: train loss: 0.4843168556690216
Batch 1000: train loss: 0.4726135730743408
Batch 1100: train loss: 0.5884807109832764
Batch 1200: train loss: 0.5188283920288086
Batch 1300: train loss: 0.5414413809776306
Batch 1400: train loss: 0.5210988521575928
Batch 1500: train loss: 0.49274909496307373
Batch 1600: train loss: 0.48038238286972046
Batch 1700: train loss: 0.575564980506897
Batch 1800: train loss: 0.46855002641677856
Batch 1900: train loss: 0.5580404996871948
Validation Batch 0: loss: 0.5018405914306641
Validation Batch 100: loss: 0.5237210392951965
Validation Batch 200: loss: 0.5066909790039062
Validation Batch 300: loss: 0.4857603907585144
Validation Batch 400: loss: 0.4996083974838257
Validation Batch 500: loss: 0.5656390190124512
Validation Batch 600: loss: 0.5368179082870483
Validation Batch 700: loss: 0.49200671911239624
AVERAGE BATCH VAL LOSS = 0.5083903670310974
EPOCH:  5
Batch 0: train loss: 0.5147150754928589
Batch 100: train loss: 0.42663341760635376
Batch 200: train loss: 0.6150031685829163
Batch 300: train loss: 0.4232652187347412
Batch 400: train loss: 0.48138192296028137
Batch 500: train loss: 0.4596741795539856
Batch 600: train loss: 0.5388542413711548
Batch 700: train loss: 0.5249038338661194
Batch 800: train loss: 0.46318966150283813
Batch 900: train loss: 0.5214426517486572
Batch 1000: train loss: 0.47265294194221497
Batch 1100: train loss: 0.4882623851299286
Batch 1200: train loss: 0.4600965678691864
Batch 1300: train loss: 0.4308028221130371
Batch 1400: train loss: 0.5366061925888062
Batch 1500: train loss: 0.5224161744117737
Batch 1600: train loss: 0.6381095051765442
Batch 1700: train loss: 0.45466408133506775
Batch 1800: train loss: 0.49228912591934204
Batch 1900: train loss: 0.4818447232246399
Validation Batch 0: loss: 0.5273074507713318
Validation Batch 100: loss: 0.5936846137046814
Validation Batch 200: loss: 0.49829936027526855
Validation Batch 300: loss: 0.5148435831069946
Validation Batch 400: loss: 0.5137131214141846
Validation Batch 500: loss: 0.5643787384033203
Validation Batch 600: loss: 0.5654394030570984
Validation Batch 700: loss: 0.4799019694328308
AVERAGE BATCH VAL LOSS = 0.5246962904930115
EPOCH:  6
Batch 0: train loss: 0.581484854221344
Batch 100: train loss: 0.47158926725387573
Batch 200: train loss: 0.43446484208106995
Batch 300: train loss: 0.487470418214798
Batch 400: train loss: 0.4322778284549713
Batch 500: train loss: 0.5405319929122925
Batch 600: train loss: 0.4842636287212372
Batch 700: train loss: 0.6082600951194763
Batch 800: train loss: 0.46361875534057617
Batch 900: train loss: 0.4522048234939575
Batch 1000: train loss: 0.4336106777191162
Batch 1100: train loss: 0.4905606806278229
Batch 1200: train loss: 0.5603343844413757

Batch 1300: train loss: 0.40102192759513855
Batch 1400: train loss: 0.46288397908210754
Batch 1500: train loss: 0.48143908381462097
Batch 1600: train loss: 0.4813075065612793
Batch 1700: train loss: 0.4656256139278412
Batch 1800: train loss: 0.44055482745170593
Batch 1900: train loss: 0.42344292998313904
Validation Batch 0: loss: 0.5646031498908997
Validation Batch 100: loss: 0.5968765616416931
Validation Batch 200: loss: 0.5530039668083191
Validation Batch 300: loss: 0.5807088613510132
Validation Batch 400: loss: 0.5985207557678223
Validation Batch 500: loss: 0.5514533519744873
Validation Batch 600: loss: 0.5873332619667053
Validation Batch 700: loss: 0.6319698691368103
AVERAGE BATCH VAL LOSS = 0.5834447741508484
EPOCH:  7
Batch 0: train loss: 0.542596161365509
Batch 100: train loss: 0.4183816909790039
Batch 200: train loss: 0.41279712319374084
Batch 300: train loss: 0.4794159233570099
Batch 400: train loss: 0.4548145532608032
Batch 500: train loss: 0.5760714411735535
Batch 600: train loss: 0.5434620976448059
Batch 700: train loss: 0.41451942920684814
Batch 800: train loss: 0.439308762550354
Batch 900: train loss: 0.5149418711662292
Batch 1000: train loss: 0.4120475649833679
Batch 1100: train loss: 0.44960540533065796
Batch 1200: train loss: 0.43815183639526367
Batch 1300: train loss: 0.5021599531173706
Batch 1400: train loss: 0.547557532787323
Batch 1500: train loss: 0.462054967880249
Batch 1600: train loss: 0.552623450756073
Batch 1700: train loss: 0.46880125999450684
Batch 1800: train loss: 0.43247663974761963
Batch 1900: train loss: 0.46657538414001465
Validation Batch 0: loss: 0.5789846181869507
Validation Batch 100: loss: 0.6298853158950806
Validation Batch 200: loss: 0.6284984350204468
Validation Batch 300: loss: 0.5843355059623718
Validation Batch 400: loss: 0.6284404993057251
Validation Batch 500: loss: 0.580022394657135
Validation Batch 600: loss: 0.5418415665626526
Validation Batch 700: loss: 0.6260729432106018
AVERAGE BATCH VAL LOSS = 0.5786359310150146
EPOCH:  8
Batch 0: train loss: 0.5659554600715637
Batch 100: train loss: 0.4877263903617859
Batch 200: train loss: 0.37569838762283325
Batch 300: train loss: 0.42874687910079956
Batch 400: train loss: 0.4808868169784546
Batch 500: train loss: 0.36347079277038574
Batch 600: train loss: 0.4523651599884033
Batch 700: train loss: 0.4760289490222931
Batch 800: train loss: 0.4239880442619324
Batch 900: train loss: 0.43546515703201294
Batch 1000: train loss: 0.40595632791519165
Batch 1100: train loss: 0.4421966075897217
Batch 1200: train loss: 0.4238217771053314
Batch 1300: train loss: 0.4367292523384094
Batch 1400: train loss: 0.4444665312767029
Batch 1500: train loss: 0.43853822350502014
Batch 1600: train loss: 0.44606518745422363
Batch 1700: train loss: 0.4442354738712311
Batch 1800: train loss: 0.47963374853134155
Batch 1900: train loss: 0.4161900281906128
Validation Batch 0: loss: 0.4941658079624176
Validation Batch 100: loss: 0.447605162858963
Validation Batch 200: loss: 0.4972453713417053
Validation Batch 300: loss: 0.3857761323451996
Validation Batch 400: loss: 0.5155587196350098
Validation Batch 500: loss: 0.45559874176979065
Validation Batch 600: loss: 0.4527590274810791
Validation Batch 700: loss: 0.5375921726226807
AVERAGE BATCH VAL LOSS = 0.48235583305358887
EPOCH:  9
Batch 0: train loss: 0.3906514644622803
Batch 100: train loss: 0.4567178189754486
Batch 200: train loss: 0.48628583550453186
Batch 300: train loss: 0.4837624728679657
Batch 400: train loss: 0.4241328537464142
Batch 500: train loss: 0.5286203622817993
Batch 600: train loss: 0.5128552913665771
Batch 700: train loss: 0.38394826650619507
Batch 800: train loss: 0.4478561282157898
Batch 900: train loss: 0.41155630350112915
Batch 1000: train loss: 0.46095600724220276
Batch 1100: train loss: 0.37898245453834534
Batch 1200: train loss: 0.42826488614082336
Batch 1300: train loss: 0.457922101020813
Batch 1400: train loss: 0.5016650557518005
Batch 1500: train loss: 0.4247267544269562
Batch 1600: train loss: 0.5080946683883667
Batch 1700: train loss: 0.48592260479927063
Batch 1800: train loss: 0.4198571443557739
Batch 1900: train loss: 0.4100121557712555
Validation Batch 0: loss: 0.5351680517196655
Validation Batch 100: loss: 0.46930527687072754
Validation Batch 200: loss: 0.4992145001888275
Validation Batch 300: loss: 0.47189560532569885
Validation Batch 400: loss: 0.4953867793083191
Validation Batch 500: loss: 0.501592218875885
Validation Batch 600: loss: 0.4568960666656494
Validation Batch 700: loss: 0.5331122279167175
AVERAGE BATCH VAL LOSS = 0.5073548555374146
EPOCH:  10
Batch 0: train loss: 0.4041599631309509
Batch 100: train loss: 0.45065200328826904
Batch 200: train loss: 0.5191113948822021
Batch 300: train loss: 0.506498396396637
Batch 400: train loss: 0.4421922564506531
Batch 500: train loss: 0.4635874032974243
Batch 600: train loss: 0.48680195212364197
Batch 700: train loss: 0.4457933306694031
Batch 800: train loss: 0.46925464272499084
Batch 900: train loss: 0.41309112310409546
Batch 1000: train loss: 0.4588663876056671
Batch 1100: train loss: 0.4897748827934265
Batch 1200: train loss: 0.47289949655532837
Batch 1300: train loss: 0.47146832942962646
Batch 1400: train loss: 0.4128427803516388
Batch 1500: train loss: 0.5163272023200989
Batch 1600: train loss: 0.398284375667572
Batch 1700: train loss: 0.41436800360679626
Batch 1800: train loss: 0.4999394714832306
Batch 1900: train loss: 0.4781845510005951
Validation Batch 0: loss: 0.4655531942844391
Validation Batch 100: loss: 0.45984479784965515
Validation Batch 200: loss: 0.525388777256012
Validation Batch 300: loss: 0.38971537351608276
Validation Batch 400: loss: 0.43291234970092773
Validation Batch 500: loss: 0.3752381205558777
Validation Batch 600: loss: 0.4933563768863678
Validation Batch 700: loss: 0.49336379766464233
AVERAGE BATCH VAL LOSS = 0.4848613440990448
EPOCH:  11
Batch 0: train loss: 0.4065590798854828
Batch 100: train loss: 0.44601941108703613
Batch 200: train loss: 0.4666025638580322
Batch 300: train loss: 0.414528489112854
Batch 400: train loss: 0.4817378520965576
Batch 500: train loss: 0.5181334018707275
Batch 600: train loss: 0.5024533271789551
Batch 700: train loss: 0.42236968874931335
Batch 800: train loss: 0.43398287892341614
Batch 900: train loss: 0.5335686802864075
Batch 1000: train loss: 0.4436963200569153
Batch 1100: train loss: 0.43561723828315735
Batch 1200: train loss: 0.48891544342041016
Batch 1300: train loss: 0.45336851477622986
Batch 1400: train loss: 0.4218735694885254
Batch 1500: train loss: 0.5384089946746826
Batch 1600: train loss: 0.42413318157196045
Batch 1700: train loss: 0.44777393341064453
Batch 1800: train loss: 0.49729353189468384
Batch 1900: train loss: 0.4153667986392975
Validation Batch 0: loss: 0.6504479646682739
Validation Batch 100: loss: 0.6701245307922363
Validation Batch 200: loss: 0.6306376457214355
Validation Batch 300: loss: 0.6485786437988281
Validation Batch 400: loss: 0.7214136123657227
Validation Batch 500: loss: 0.7214632630348206
Validation Batch 600: loss: 0.5958787202835083
Validation Batch 700: loss: 0.5922065377235413
AVERAGE BATCH VAL LOSS = 0.6683496832847595
EPOCH:  12
Batch 0: train loss: 0.46853601932525635
Batch 100: train loss: 0.43025505542755127
Batch 200: train loss: 0.44936373829841614
Batch 300: train loss: 0.4123245179653168
Batch 400: train loss: 0.476595938205719
Batch 500: train loss: 0.3959118723869324
Batch 600: train loss: 0.4436718225479126
Batch 700: train loss: 0.40041467547416687
Batch 800: train loss: 0.44598233699798584
Batch 900: train loss: 0.46001291275024414
Batch 1000: train loss: 0.36816808581352234
Batch 1100: train loss: 0.3813822269439697
Batch 1200: train loss: 0.41746795177459717
Batch 1300: train loss: 0.35454756021499634
Batch 1400: train loss: 0.5010709166526794
Batch 1500: train loss: 0.47504758834838867
Batch 1600: train loss: 0.4791678786277771
Batch 1700: train loss: 0.5005857944488525
Batch 1800: train loss: 0.3411813974380493
Batch 1900: train loss: 0.4242408275604248
Validation Batch 0: loss: 0.6200711727142334
Validation Batch 100: loss: 0.5505332946777344
Validation Batch 200: loss: 0.5473602414131165
Validation Batch 300: loss: 0.5658838748931885

Validation Batch 400: loss: 0.484864205121994
Validation Batch 500: loss: 0.5356382131576538
Validation Batch 600: loss: 0.47629883885383606
Validation Batch 700: loss: 0.5585200786590576
AVERAGE BATCH VAL LOSS = 0.5376240611076355
EPOCH:  13
Batch 0: train loss: 0.40627044439315796
Batch 100: train loss: 0.4003274440765381
Batch 200: train loss: 0.42251259088516235
Batch 300: train loss: 0.4075794816017151
Batch 400: train loss: 0.5216246843338013
Batch 500: train loss: 0.4910753667354584
Batch 600: train loss: 0.33936256170272827
Batch 700: train loss: 0.40404874086380005
Batch 800: train loss: 0.4739995300769806
Batch 900: train loss: 0.5096544623374939
Batch 1000: train loss: 0.4021013379096985
Batch 1100: train loss: 0.4315601587295532
Batch 1200: train loss: 0.37040552496910095
Batch 1300: train loss: 0.4129425585269928
Batch 1400: train loss: 0.4029676616191864
Batch 1500: train loss: 0.43003198504447937
Batch 1600: train loss: 0.3570355176925659
Batch 1700: train loss: 0.36547720432281494
Batch 1800: train loss: 0.3666056990623474
Batch 1900: train loss: 0.4069773256778717
Validation Batch 0: loss: 0.5183103084564209
Validation Batch 100: loss: 0.43151581287384033
Validation Batch 200: loss: 0.4189567565917969
Validation Batch 300: loss: 0.43277695775032043
Validation Batch 400: loss: 0.45926904678344727
Validation Batch 500: loss: 0.4332519471645355
Validation Batch 600: loss: 0.360002726316452
Validation Batch 700: loss: 0.4243218004703522
AVERAGE BATCH VAL LOSS = 0.44505074620246887
EPOCH:  14
Batch 0: train loss: 0.6202107071876526
Batch 100: train loss: 0.4352464973926544
Batch 200: train loss: 0.46803513169288635
Batch 300: train loss: 0.4154675304889679
Batch 400: train loss: 0.3343268036842346
Batch 500: train loss: 0.4527297616004944
Batch 600: train loss: 0.4521482586860657
Batch 700: train loss: 0.4694706201553345
Batch 800: train loss: 0.425666868686676
Batch 900: train loss: 0.4197707772254944
Batch 1000: train loss: 0.3955681324005127
Batch 1100: train loss: 0.37443041801452637
Batch 1200: train loss: 0.36152249574661255
Batch 1300: train loss: 0.3464621603488922
Batch 1400: train loss: 0.355487585067749
Batch 1500: train loss: 0.44169366359710693
Batch 1600: train loss: 0.3658427894115448
Batch 1700: train loss: 0.3685508668422699
Batch 1800: train loss: 0.5472606420516968
Batch 1900: train loss: 0.3606865108013153
Validation Batch 0: loss: 0.6014191508293152
Validation Batch 100: loss: 0.4906837046146393
Validation Batch 200: loss: 0.6596411466598511
Validation Batch 300: loss: 0.5870118737220764
Validation Batch 400: loss: 0.6683009266853333
Validation Batch 500: loss: 0.6295571327209473
Validation Batch 600: loss: 0.6633017063140869
Validation Batch 700: loss: 0.5594857335090637
AVERAGE BATCH VAL LOSS = 0.6305885910987854
EPOCH:  15
Batch 0: train loss: 0.5813379287719727
Batch 100: train loss: 0.3936951160430908
Batch 200: train loss: 0.44284287095069885
Batch 300: train loss: 0.4303692877292633
Batch 400: train loss: 0.42733901739120483
Batch 500: train loss: 0.4722578823566437
Batch 600: train loss: 0.3900197744369507
Batch 700: train loss: 0.3818330466747284
Batch 800: train loss: 0.37297388911247253
Batch 900: train loss: 0.3696938753128052
Batch 1000: train loss: 0.4561481773853302
Batch 1100: train loss: 0.3242875337600708
Batch 1200: train loss: 0.42115694284439087
Batch 1300: train loss: 0.4323331117630005
Batch 1400: train loss: 0.34837663173675537
Batch 1500: train loss: 0.3596747815608978
Batch 1600: train loss: 0.37168195843696594
Batch 1700: train loss: 0.4328124225139618
Batch 1800: train loss: 0.3848656415939331
Batch 1900: train loss: 0.41864174604415894
Validation Batch 0: loss: 0.5391218066215515
Validation Batch 100: loss: 0.5147626399993896
Validation Batch 200: loss: 0.583211362361908
Validation Batch 300: loss: 0.6029220223426819
Validation Batch 400: loss: 0.5022808313369751
Validation Batch 500: loss: 0.6337706446647644
Validation Batch 600: loss: 0.5778001546859741
Validation Batch 700: loss: 0.6116798520088196
AVERAGE BATCH VAL LOSS = 0.5964236855506897
EPOCH:  16
Batch 0: train loss: 0.5664392709732056
Batch 100: train loss: 0.3830046057701111
Batch 200: train loss: 0.45146140456199646
Batch 300: train loss: 0.4192390441894531
Batch 400: train loss: 0.3259632885456085
Batch 500: train loss: 0.5428328514099121
Batch 600: train loss: 0.4176231026649475
Batch 700: train loss: 0.4128752052783966
Batch 800: train loss: 0.5243250727653503
Batch 900: train loss: 0.4587606191635132
Batch 1000: train loss: 0.39493075013160706
Batch 1100: train loss: 0.3542345464229584
Batch 1200: train loss: 0.4668874442577362
Batch 1300: train loss: 0.41028475761413574
Batch 1400: train loss: 0.44765812158584595
Batch 1500: train loss: 0.4046735465526581
Batch 1600: train loss: 0.4870091378688812
Batch 1700: train loss: 0.5025975704193115
Batch 1800: train loss: 0.5013790726661682
Batch 1900: train loss: 0.39342042803764343
Validation Batch 0: loss: 0.40922725200653076
Validation Batch 100: loss: 0.41583701968193054
Validation Batch 200: loss: 0.34970444440841675
Validation Batch 300: loss: 0.40707916021347046
Validation Batch 400: loss: 0.4935914874076843
Validation Batch 500: loss: 0.42237746715545654
Validation Batch 600: loss: 0.4433717131614685
Validation Batch 700: loss: 0.3434658944606781
AVERAGE BATCH VAL LOSS = 0.4176279902458191
EPOCH:  17
Batch 0: train loss: 0.46024325489997864
Batch 100: train loss: 0.34084367752075195
Batch 200: train loss: 0.3825262486934662
Batch 300: train loss: 0.45117226243019104
Batch 400: train loss: 0.47636252641677856
Batch 500: train loss: 0.44099676609039307
Batch 600: train loss: 0.46370044350624084
Batch 700: train loss: 0.5162869691848755
Batch 800: train loss: 0.3828078508377075
Batch 900: train loss: 0.3805185556411743
Batch 1000: train loss: 0.392978698015213
Batch 1100: train loss: 0.36838632822036743
Batch 1200: train loss: 0.4583328068256378
Batch 1300: train loss: 0.41773754358291626
Batch 1400: train loss: 0.45611491799354553
Batch 1500: train loss: 0.3564354181289673
Batch 1600: train loss: 0.29642003774642944
Batch 1700: train loss: 0.4147968888282776
Batch 1800: train loss: 0.47198033332824707
Batch 1900: train loss: 0.4376721978187561
Validation Batch 0: loss: 0.4982367157936096
Validation Batch 100: loss: 0.5297473073005676
Validation Batch 200: loss: 0.5318915843963623
Validation Batch 300: loss: 0.5055997371673584
Validation Batch 400: loss: 0.3949885070323944
Validation Batch 500: loss: 0.5059135556221008
Validation Batch 600: loss: 0.543738067150116
Validation Batch 700: loss: 0.47615066170692444
AVERAGE BATCH VAL LOSS = 0.5080358982086182
EPOCH:  18
Batch 0: train loss: 0.41851648688316345
Batch 100: train loss: 0.44935575127601624
Batch 200: train loss: 0.3652631640434265
Batch 300: train loss: 0.45250263810157776
Batch 400: train loss: 0.3496478199958801
Batch 500: train loss: 0.4730663597583771
Batch 600: train loss: 0.375795841217041
Batch 700: train loss: 0.43512073159217834
Batch 800: train loss: 0.36044347286224365
Batch 900: train loss: 0.44538944959640503
Batch 1000: train loss: 0.3607213497161865
Batch 1100: train loss: 0.422548770904541
Batch 1200: train loss: 0.415693998336792
Batch 1300: train loss: 0.4016123116016388
Batch 1400: train loss: 0.4326014220714569
Batch 1500: train loss: 0.3710576891899109
Batch 1600: train loss: 0.3656521141529083
Batch 1700: train loss: 0.37776121497154236
Batch 1800: train loss: 0.3332730233669281
Batch 1900: train loss: 0.31788623332977295
Validation Batch 0: loss: 0.39594370126724243
Validation Batch 100: loss: 0.4333493709564209
Validation Batch 200: loss: 0.4427887201309204
Validation Batch 300: loss: 0.41049671173095703
Validation Batch 400: loss: 0.4550416171550751
Validation Batch 500: loss: 0.4392169713973999
Validation Batch 600: loss: 0.45246052742004395
Validation Batch 700: loss: 0.40757322311401367
AVERAGE BATCH VAL LOSS = 0.42477694153785706
EPOCH:  19
Batch 0: train loss: 0.4222748279571533
Batch 100: train loss: 0.35450929403305054
Batch 200: train loss: 0.37295860052108765
Batch 300: train loss: 0.41678115725517273
Batch 400: train loss: 0.41946208477020264
Batch 500: train loss: 0.39820578694343567

Batch 600: train loss: 0.5407666563987732
Batch 700: train loss: 0.46103450655937195
Batch 800: train loss: 0.4292481243610382
Batch 900: train loss: 0.36585667729377747
Batch 1000: train loss: 0.42342036962509155
Batch 1100: train loss: 0.28076907992362976
Batch 1200: train loss: 0.48628538846969604
Batch 1300: train loss: 0.3587314784526825
Batch 1400: train loss: 0.36070677638053894
Batch 1500: train loss: 0.48541581630706787
Batch 1600: train loss: 0.4771183729171753
Batch 1700: train loss: 0.4355328381061554
Batch 1800: train loss: 0.44630977511405945
Batch 1900: train loss: 0.4355911910533905
Validation Batch 0: loss: 0.4910696744918823
Validation Batch 100: loss: 0.47192564606666565
Validation Batch 200: loss: 0.5179162621498108
Validation Batch 300: loss: 0.49711155891418457
Validation Batch 400: loss: 0.4362960755825043
Validation Batch 500: loss: 0.4333142936229706
Validation Batch 600: loss: 0.5174903273582458
Validation Batch 700: loss: 0.4869093894958496
AVERAGE BATCH VAL LOSS = 0.4976438581943512
Time elapsed in training: 815.6272933483124 seconds

52

In [13]:
torch.save(best_model, '/Users/nkerstingadxnet.com/Documents/Higgs/output/mlp.600.nophi.pt')

In [14]:
best_model.eval()
y_pred = model(torch.tensor(normed_train_data.values, dtype=torch.float)).tolist()

In [67]:
import math
def AMS(s, b):
    """ Approximate Median Significance defined as:
        AMS = sqrt(
                2 { (s + b + b_r) log[1 + (s/(b+b_r))] - s}
              )        
    where b_r = 10, b = background, s = signal, log is natural logarithm """
    
    br = 10.0
    radicand = 2 *( (s+b+br) * math.log (1.0 + s/(b+br)) -s)
    if radicand < 0:
        print('radicand is negative. Exiting')
        exit()
    else:
        return math.sqrt(radicand)

In [68]:
# Training performance
y_gold = orig_train_data['Label']
y_weight = orig_train_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y[0] > 0.5:
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TRAINING: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TRAINING: (S,B) = (592.949,70954.077), AMS=2.223, Unweighted Precision = 0.617

In [69]:
y_pred = best_model(torch.tensor(normed_public_test_data.values, dtype=torch.float)).tolist()

In [70]:
y_gold = orig_public_test_data['Label']
y_weight = orig_public_test_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y[0] > 0.5:
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"VALID: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

VALID: (S,B) = (439.916,29919.952), AMS=2.537, Unweighted Precision = 0.722

In [71]:
y_pred = best_model(torch.tensor(normed_private_test_data.values, dtype=torch.float)).tolist()

In [72]:
y_gold = orig_private_test_data['Label']
y_weight = orig_private_test_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y[0] > 0.5:
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TEST: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TEST: (S,B) = (352.093,21353.519), AMS=2.402, Unweighted Precision = 0.750

In [29]:
normed_public_test_data.head()

,DER_mass_MMC,DER_mass_transverse_met_lep,DER_mass_vis,DER_pt_h,DER_deltaeta_jet_jet,DER_mass_jet_jet,DER_prodeta_jet_jet,DER_deltar_tau_lep,DER_pt_tot,DER_sum_pt,...,PRI_lep_pt,PRI_lep_eta,PRI_met,PRI_met_sumet,PRI_jet_num,PRI_jet_leading_pt,PRI_jet_leading_eta,PRI_jet_subleading_pt,PRI_jet_subleading_eta,PRI_jet_all_pt
250000,0.101990,0.087702,0.016287,0.002270,0.286389,0.091591,0.48232,0.119433,0.003998,0.005997,...,0.011742,0.399080,0.038546,0.047809,0.0,0.048355,0.499487,0.048145,0.499026,-0.0
250008,0.055259,0.073090,0.053375,0.000567,0.286389,0.091591,0.48232,0.389400,0.000998,0.012431,...,0.022059,0.726345,0.024009,0.049964,0.0,0.048355,0.499487,0.048145,0.499026,-0.0
250017,0.027302,0.084231,0.027383,0.044529,0.286389,0.091591,0.48232,0.118881,0.078412,0.021463,...,0.044543,0.038208,0.021982,0.107759,0.0,0.048355,0.499487,0.048145,0.499026,0.0
250027,0.088151,0.088579,0.065443,0.030233,0.286389,0.091591,0.48232,0.464299,0.053238,0.016104,...,0.025524,0.902581,0.032859,0.082216,0.0,0.048355,0.499487,0.048145,0.499026,-0.0
250032,0.129668,0.061777,0.087233,0.020138,0.286389,0.091591,0.48232,0.541038,0.035461,0.016073,...,0.016909,0.321464,0.017559,0.037446,0.0,0.048355,0.499487,0.048145,0.499026,0.0

In [30]:
orig_public_test_data.head()

,EventId,DER_mass_MMC,DER_mass_transverse_met_lep,DER_mass_vis,DER_pt_h,DER_deltaeta_jet_jet,DER_mass_jet_jet,DER_prodeta_jet_jet,DER_deltar_tau_lep,DER_pt_tot,...,PRI_jet_leading_pt,PRI_jet_leading_eta,PRI_jet_subleading_pt,PRI_jet_subleading_eta,PRI_jet_all_pt,Weight,Label,KaggleSet,KaggleWeight,Binary_Label
250000,350000,NaN,79.589,23.916,3.036,NaN,NaN,NaN,0.903,3.036,...,NaN,NaN,NaN,NaN,-0.0,1.380904,b,b,11.246677,0
250008,350008,70.958,66.329,60.950,0.758,NaN,NaN,NaN,2.370,0.758,...,NaN,NaN,NaN,NaN,-0.0,1.412085,b,b,11.500627,0
250017,350017,40.383,76.439,34.996,59.543,NaN,NaN,NaN,0.900,59.543,...,NaN,NaN,NaN,NaN,0.0,0.338196,b,b,2.754413,0
250027,350027,106.932,80.385,73.001,40.427,NaN,NaN,NaN,2.777,40.427,...,NaN,NaN,NaN,NaN,-0.0,0.005721,s,b,0.046987,1
250032,350032,152.338,56.063,94.760,26.928,NaN,NaN,NaN,3.194,26.928,...,NaN,NaN,NaN,NaN,0.0,0.005721,s,b,0.046987,1

In [63]:
from datetime import datetime

now = datetime.now()
dt_string = now.strftime("%d%m%Y%H%M%S")
print("date and time =", dt_string)

date and time = 02112021102314