In [2]:
import numpy as np # linear algebra
import pandas as pd # data processing, CSV file I/O (e.g. pd.read_csv)
import matplotlib.pyplot as plt
import time

In [21]:
data=pd.read_csv('/opt/neurothink/neuro-deb05933716f4eb6be138022abf35d2f/train.csv')
test=pd.read_csv('/opt/neurothink/neuro-1d4c617f8ef0447bafed400cb9e1ff6b/test.csv')

In [26]:
data.head()
#len(test)

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [31]:
data.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype
---  ------       --------------  -----
 0   PassengerId  891 non-null    int64
 1   Survived     891 non-null    int64
 2   Pclass       891 non-null    int64
 3   Name         891 non-null    object
 4   Sex          891 non-null    object
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64
 7   Parch        891 non-null    int64
 8   Ticket       891 non-null    object
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object
 11  Embarked     889 non-null    object
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB

In [27]:
data['Age'].fillna(data['Age'].median(),inplace=True)
data.drop('Cabin',axis=1,inplace=True)
data['Embarked'].fillna('S',inplace=True)
data.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)
data['Pclass']=data['Pclass'].astype(str)
data['Accompanied']=0
for i in range(data.shape[0]):
    if (data.loc[i,'SibSp']+data.loc[i,'Parch'])>0:
        data.loc[i,'Accompanied']=1
data['Accompanied']=data['Accompanied'].astype(str)
data.drop(['SibSp','Parch'],axis=1,inplace=True)
data=pd.get_dummies(data)

In [28]:
data

,Survived,Age,Fare,Pclass_1,Pclass_2,Pclass_3,Sex_female,Sex_male,Embarked_C,Embarked_Q,Embarked_S,Accompanied_0,Accompanied_1
0,0,22.0,7.2500,0,0,1,0,1,0,0,1,0,1
1,1,38.0,71.2833,1,0,0,1,0,1,0,0,0,1
2,1,26.0,7.9250,0,0,1,1,0,0,0,1,1,0
3,1,35.0,53.1000,1,0,0,1,0,0,0,1,0,1
4,0,35.0,8.0500,0,0,1,0,1,0,0,1,1,0
...,...,...,...,...,...,...,...,...,...,...,...,...,...
886,0,27.0,13.0000,0,1,0,0,1,0,0,1,1,0
887,1,19.0,30.0000,1,0,0,1,0,0,0,1,1,0
888,0,28.0,23.4500,0,0,1,1,0,0,0,1,0,1
889,1,26.0,30.0000,1,0,0,0,1,1,0,0,1,0
890,0,32.0,7.7500,0,0,1,0,1,0,1,0,1,0

In [29]:
X=data[['Age','Fare','Pclass_1','Pclass_2','Pclass_3','Sex_female','Sex_male','Embarked_C','Embarked_Q','Embarked_S','Accompanied_0','Accompanied_1']]
y=data['Survived']

In [30]:
test['Fare'].fillna(test['Fare'].median(),inplace=True)
test['Age'].fillna(data['Age'].median(),inplace=True)
test.drop('Cabin',axis=1,inplace=True)
test['Embarked'].fillna('S',inplace=True)
test.drop(['PassengerId','Name','Ticket'],axis=1,inplace=True)
test['Pclass']=test['Pclass'].astype(str)
test['Accompanied']=0
for i in range(test.shape[0]):
    if (test.loc[i,'SibSp']+test.loc[i,'Parch'])>0:
        test.loc[i,'Accompanied']=1
test['Accompanied']=test['Accompanied'].astype(str)
test.drop(['SibSp','Parch'],axis=1,inplace=True)
test=pd.get_dummies(test)

In [31]:
from sklearn.model_selection import GridSearchCV
from xgboost.sklearn import XGBClassifier
import lightgbm as lgb
from sklearn.ensemble import GradientBoostingClassifier as gbr

In [32]:
xgb=XGBClassifier(learning_rate=0.1,n_estimators=500,max_depth=5,min_child_weight=1,gamma=0,
subsample=0.8,colsample_bytree=0.8,objective= 'binary:logistic',seed=0)

In [12]:
start = time.time_ns()
param_test = {'n_estimators':range(30,40,50)}
gs = GridSearchCV(estimator = xgb,param_grid = param_test, scoring='roc_auc',n_jobs=-1,cv=5)
gs.fit(X,y)
print(gs.best_params_,gs.best_score_)
print(gs.cv_results_['mean_test_score'])
end = time.time_ns()
print('**************')
print('TIME USED (ms):', (end-start)/1000)

/opt/conda/lib/python3.9/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/opt/conda/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/opt/conda/lib/python3.9/site-packages/xgboost/data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
/opt/conda/lib/python3.9/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/opt/conda/lib/python3.9/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/opt/conda/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/opt/conda/lib/python3.9/site-packages/xgboost/data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
/opt/conda/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/opt/conda/lib/python3.9/site-packages/xgboost/data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
/opt/conda/lib/python3.9/site-packages/xgboost/compat.py:36: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  from pandas import MultiIndex, Int64Index
/opt/conda/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/opt/conda/lib/python3.9/site-packages/xgboost/data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
/opt/conda/lib/python3.9/site-packages/xgboost/data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
/opt/conda/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/opt/conda/lib/python3.9/site-packages/xgboost/data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
/opt/conda/lib/python3.9/site-packages/xgboost/data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
/opt/conda/lib/python3.9/site-packages/xgboost/data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
/opt/conda/lib/python3.9/site-packages/xgboost/data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
/opt/conda/lib/python3.9/site-packages/xgboost/data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):
/opt/conda/lib/python3.9/site-packages/xgboost/sklearn.py:1224: UserWarning: The use of label encoder in XGBClassifier is deprecated and will be removed in a future release. To remove this warning, do the following: 1) Pass option use_label_encoder=False when constructing XGBClassifier object; and 2) Encode your labels (y) as integers starting with 0, i.e. 0, 1, 2, ..., [num_class - 1].
  warnings.warn(label_encoder_deprecation_msg, UserWarning)
/opt/conda/lib/python3.9/site-packages/xgboost/data.py:262: FutureWarning: pandas.Int64Index is deprecated and will be removed from pandas in a future version. Use pandas.Index with the appropriate dtype instead.
  elif isinstance(data.columns, (pd.Int64Index, pd.RangeIndex)):

[03:52:56] WARNING: ../src/learner.cc:1115: Starting in XGBoost 1.3.0, the default evaluation metric used with the objective 'binary:logistic' was changed from 'error' to 'logloss'. Explicitly set eval_metric if you'd like to restore the old behavior.
{'n_estimators': 30} 0.8684815528996529
[0.86848155]
**************
TIME USED (ms): 476564962.324

In [47]:
#!pip install catboost

Collecting catboost
  Downloading catboost-1.0.4-cp39-none-manylinux1_x86_64.whl (76.2 MB)
     |████████████████████████████████| 76.2 MB 219 kB/s
Requirement already satisfied: matplotlib in /opt/conda/lib/python3.9/site-packages (from catboost) (3.5.1)
Requirement already satisfied: plotly in /opt/conda/lib/python3.9/site-packages (from catboost) (4.14.3)
Requirement already satisfied: scipy in /opt/conda/lib/python3.9/site-packages (from catboost) (1.7.3)
Requirement already satisfied: six in /opt/conda/lib/python3.9/site-packages (from catboost) (1.16.0)
Requirement already satisfied: graphviz in /opt/conda/lib/python3.9/site-packages (from catboost) (0.19.1)
Requirement already satisfied: numpy>=1.16.0 in /opt/conda/lib/python3.9/site-packages (from catboost) (1.22.1)
Requirement already satisfied: pandas>=0.24.0 in /opt/conda/lib/python3.9/site-packages (from catboost) (1.4.0)
Requirement already satisfied: pytz>=2020.1 in /opt/conda/lib/python3.9/site-packages (from pandas>=0.24.0->catboost) (2021.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /opt/conda/lib/python3.9/site-packages (from pandas>=0.24.0->catboost) (2.8.2)
Requirement already satisfied: pyparsing>=2.2.1 in /opt/conda/lib/python3.9/site-packages (from matplotlib->catboost) (3.0.7)
Requirement already satisfied: packaging>=20.0 in /opt/conda/lib/python3.9/site-packages (from matplotlib->catboost) (21.3)
Requirement already satisfied: fonttools>=4.22.0 in /opt/conda/lib/python3.9/site-packages (from matplotlib->catboost) (4.29.0)
Requirement already satisfied: pillow>=6.2.0 in /opt/conda/lib/python3.9/site-packages (from matplotlib->catboost) (9.0.0)
Requirement already satisfied: cycler>=0.10 in /opt/conda/lib/python3.9/site-packages (from matplotlib->catboost) (0.11.0)
Requirement already satisfied: kiwisolver>=1.0.1 in /opt/conda/lib/python3.9/site-packages (from matplotlib->catboost) (1.3.2)
Requirement already satisfied: retrying>=1.3.3 in /opt/conda/lib/python3.9/site-packages (from plotly->catboost) (1.3.3)
Installing collected packages: catboost
Successfully installed catboost-1.0.4

In [33]:
from catboost import CatBoostClassifier

cat = CatBoostClassifier(eval_metric='Accuracy', use_best_model=True,  random_seed=42)

In [34]:
param_test = {'iterations':[30,40,50], 'use_best_model': [False]}
"""
params = {'depth':[3,1,2,6,4,5,7,8,9,10],
          'iterations':[250,100,500,1000],
          'learning_rate':[0.03,0.001,0.01,0.1,0.2,0.3], 
          'l2_leaf_reg':[3,1,5,10,100],
          'border_count':[32,5,10,20,50,100,200],
          'ctr_border_count':[50,5,10,20,100,200],
          'thread_count':4}
"""
start = time.time_ns()
gs_cat = GridSearchCV(estimator = cat, param_grid = param_test, scoring='roc_auc',n_jobs=-1,cv=5)
gs_cat.fit(X,y)
print(gs_cat.best_params_,gs_cat.best_score_)
print(gs_cat.cv_results_['mean_test_score'])
end = time.time_ns()
print('**************')
print('TIME USED (ms):', (end-start)/1000)

Learning rate set to 0.222169
0:	learn: 0.7826087	total: 47.3ms	remaining: 1.37s
1:	learn: 0.8106592	total: 48ms	remaining: 672ms
2:	learn: 0.8204769	total: 49.3ms	remaining: 444ms
3:	learn: 0.8288920	total: 50ms	remaining: 325ms
4:	learn: 0.8274895	total: 50.7ms	remaining: 253ms
5:	learn: 0.8260870	total: 51.3ms	remaining: 205ms
6:	learn: 0.8302945	total: 52ms	remaining: 171ms
7:	learn: 0.8373072	total: 52.9ms	remaining: 146ms
8:	learn: 0.8302945	total: 53.2ms	remaining: 124ms
9:	learn: 0.8274895	total: 53.9ms	remaining: 108ms
10:	learn: 0.8330996	total: 54.6ms	remaining: 94.3ms
11:	learn: 0.8373072	total: 55.3ms	remaining: 82.9ms
12:	learn: 0.8345021	total: 55.7ms	remaining: 72.8ms
13:	learn: 0.8345021	total: 56.3ms	remaining: 64.4ms
14:	learn: 0.8330996	total: 57.8ms	remaining: 57.8ms
15:	learn: 0.8359046	total: 58.4ms	remaining: 51.1ms
16:	learn: 0.8330996	total: 59.1ms	remaining: 45.2ms
17:	learn: 0.8401122	total: 59.7ms	remaining: 39.8ms
18:	learn: 0.8429173	total: 61.1ms	remaining: 35.4ms
19:	learn: 0.8415147	total: 61.8ms	remaining: 30.9ms
20:	learn: 0.8457223	total: 62.5ms	remaining: 26.8ms
21:	learn: 0.8513324	total: 63.2ms	remaining: 23ms
22:	learn: 0.8527349	total: 63.8ms	remaining: 19.4ms
23:	learn: 0.8625526	total: 64.7ms	remaining: 16.2ms
24:	learn: 0.8583450	total: 65.4ms	remaining: 13.1ms
25:	learn: 0.8611501	total: 66.1ms	remaining: 10.2ms
26:	learn: 0.8625526	total: 66.7ms	remaining: 7.42ms
27:	learn: 0.8639551	total: 67.5ms	remaining: 4.82ms
28:	learn: 0.8667602	total: 68.1ms	remaining: 2.35ms
29:	learn: 0.8667602	total: 68.8ms	remaining: 0us
Learning rate set to 0.170551
0:	learn: 0.8244382	total: 795us	remaining: 31ms
1:	learn: 0.8272472	total: 1.51ms	remaining: 28.8ms
2:	learn: 0.8328652	total: 2.25ms	remaining: 27.7ms
3:	learn: 0.8314607	total: 2.97ms	remaining: 26.7ms
4:	learn: 0.8328652	total: 3.67ms	remaining: 25.7ms
5:	learn: 0.8356742	total: 4.45ms	remaining: 25.2ms
6:	learn: 0.8272472	total: 7.33ms	remaining: 34.6ms
7:	learn: 0.8258427	total: 8.06ms	remaining: 32.2ms
8:	learn: 0.8258427	total: 8.26ms	remaining: 28.5ms
9:	learn: 0.8258427	total: 8.98ms	remaining: 26.9ms
10:	learn: 0.8286517	total: 9.7ms	remaining: 25.6ms
11:	learn: 0.8300562	total: 10.4ms	remaining: 24.3ms
12:	learn: 0.8328652	total: 11.1ms	remaining: 23.1ms
13:	learn: 0.8300562	total: 12ms	remaining: 22.3ms
14:	learn: 0.8328652	total: 12.3ms	remaining: 20.5ms
15:	learn: 0.8370787	total: 13ms	remaining: 19.4ms
16:	learn: 0.8384831	total: 13.6ms	remaining: 18.4ms
17:	learn: 0.8426966	total: 14.3ms	remaining: 17.5ms
18:	learn: 0.8412921	total: 15.1ms	remaining: 16.7ms
19:	learn: 0.8412921	total: 15.8ms	remaining: 15.8ms
20:	learn: 0.8412921	total: 16.5ms	remaining: 14.9ms
21:	learn: 0.8412921	total: 17.1ms	remaining: 14ms
22:	learn: 0.8384831	total: 17.8ms	remaining: 13.2ms
23:	learn: 0.8426966	total: 18.5ms	remaining: 12.3ms
24:	learn: 0.8426966	total: 19.2ms	remaining: 11.5ms
25:	learn: 0.8412921	total: 19.8ms	remaining: 10.7ms
26:	learn: 0.8426966	total: 20.5ms	remaining: 9.88ms
27:	learn: 0.8469101	total: 21.2ms	remaining: 9.07ms
28:	learn: 0.8525281	total: 21.8ms	remaining: 8.27ms
29:	learn: 0.8525281	total: 22.5ms	remaining: 7.49ms
30:	learn: 0.8525281	total: 23.1ms	remaining: 6.72ms
31:	learn: 0.8511236	total: 23.8ms	remaining: 5.94ms
32:	learn: 0.8539326	total: 24.4ms	remaining: 5.18ms
33:	learn: 0.8511236	total: 25.1ms	remaining: 4.44ms
34:	learn: 0.8483146	total: 25.9ms	remaining: 3.69ms
35:	learn: 0.8497191	total: 26.3ms	remaining: 2.92ms
36:	learn: 0.8497191	total: 27ms	remaining: 2.19ms
37:	learn: 0.8497191	total: 27.7ms	remaining: 1.46ms
38:	learn: 0.8483146	total: 28.5ms	remaining: 729us
39:	learn: 0.8497191	total: 28.9ms	remaining: 0us
Learning rate set to 0.170653
0:	learn: 0.8176718	total: 753us	remaining: 29.4ms
1:	learn: 0.8176718	total: 1.45ms	remaining: 27.6ms
2:	learn: 0.8162693	total: 2.14ms	remaining: 26.4ms
3:	learn: 0.8232819	total: 2.83ms	remaining: 25.5ms
4:	learn: 0.8162693	total: 3.52ms	remaining: 24.6ms
5:	learn: 0.8190743	total: 4.25ms	remaining: 24.1ms
6:	learn: 0.8176718	total: 4.93ms	remaining: 23.2ms
7:	learn: 0.8190743	total: 5.61ms	remaining: 22.4ms
8:	learn: 0.8246844	total: 5.78ms	remaining: 19.9ms
9:	learn: 0.8274895	total: 6.44ms	remaining: 19.3ms
10:	learn: 0.8232819	total: 7.12ms	remaining: 18.8ms
11:	learn: 0.8274895	total: 7.82ms	remaining: 18.2ms
12:	learn: 0.8260870	total: 8.5ms	remaining: 17.7ms
13:	learn: 0.8260870	total: 9.18ms	remaining: 17ms
14:	learn: 0.8274895	total: 9.46ms	remaining: 15.8ms
15:	learn: 0.8316971	total: 10.1ms	remaining: 15.2ms
16:	learn: 0.8260870	total: 10.8ms	remaining: 14.6ms
17:	learn: 0.8274895	total: 11.5ms	remaining: 14ms
18:	learn: 0.8330996	total: 12.1ms	remaining: 13.4ms
19:	learn: 0.8316971	total: 12.8ms	remaining: 12.8ms
20:	learn: 0.8316971	total: 13.5ms	remaining: 12.2ms
21:	learn: 0.8302945	total: 14.1ms	remaining: 11.5ms
22:	learn: 0.8359046	total: 14.7ms	remaining: 10.9ms
23:	learn: 0.8345021	total: 15.4ms	remaining: 10.3ms
24:	learn: 0.8373072	total: 16.1ms	remaining: 9.65ms
25:	learn: 0.8359046	total: 16.8ms	remaining: 9.03ms
26:	learn: 0.8373072	total: 17.4ms	remaining: 8.39ms
27:	learn: 0.8401122	total: 18.1ms	remaining: 7.74ms
28:	learn: 0.8387097	total: 18.7ms	remaining: 7.1ms
29:	learn: 0.8429173	total: 19.4ms	remaining: 6.46ms
30:	learn: 0.8443198	total: 20ms	remaining: 5.82ms
31:	learn: 0.8457223	total: 20.7ms	remaining: 5.17ms
32:	learn: 0.8485273	total: 21.3ms	remaining: 4.51ms
33:	learn: 0.8457223	total: 21.9ms	remaining: 3.87ms
34:	learn: 0.8485273	total: 22.1ms	remaining: 3.16ms
35:	learn: 0.8527349	total: 22.8ms	remaining: 2.53ms
36:	learn: 0.8471248	total: 23.4ms	remaining: 1.9ms
37:	learn: 0.8499299	total: 24ms	remaining: 1.26ms
38:	learn: 0.8499299	total: 24.7ms	remaining: 633us
39:	learn: 0.8471248	total: 25.3ms	remaining: 0us
Learning rate set to 0.139075
0:	learn: 0.8274895	total: 719us	remaining: 35.3ms
1:	learn: 0.8162693	total: 1.02ms	remaining: 24.5ms
2:	learn: 0.8106592	total: 1.7ms	remaining: 26.7ms
3:	learn: 0.8274895	total: 2.39ms	remaining: 27.5ms
4:	learn: 0.8316971	total: 3.06ms	remaining: 27.5ms
5:	learn: 0.8302945	total: 3.71ms	remaining: 27.2ms
6:	learn: 0.8316971	total: 4.36ms	remaining: 26.8ms
7:	learn: 0.8316971	total: 5.04ms	remaining: 26.4ms
8:	learn: 0.8302945	total: 5.36ms	remaining: 24.4ms
9:	learn: 0.8387097	total: 6.05ms	remaining: 24.2ms
10:	learn: 0.8316971	total: 6.75ms	remaining: 23.9ms
11:	learn: 0.8387097	total: 7.42ms	remaining: 23.5ms
12:	learn: 0.8330996	total: 8.13ms	remaining: 23.1ms
13:	learn: 0.8401122	total: 8.79ms	remaining: 22.6ms
14:	learn: 0.8359046	total: 9.09ms	remaining: 21.2ms
15:	learn: 0.8429173	total: 9.76ms	remaining: 20.7ms
16:	learn: 0.8387097	total: 10.5ms	remaining: 20.3ms
17:	learn: 0.8429173	total: 11.2ms	remaining: 19.8ms
18:	learn: 0.8443198	total: 11.8ms	remaining: 19.3ms
19:	learn: 0.8429173	total: 12.5ms	remaining: 18.8ms
20:	learn: 0.8457223	total: 13.1ms	remaining: 18.1ms
21:	learn: 0.8429173	total: 13.8ms	remaining: 17.5ms
22:	learn: 0.8457223	total: 14.4ms	remaining: 16.9ms
23:	learn: 0.8443198	total: 15.1ms	remaining: 16.3ms
24:	learn: 0.8485273	total: 15.7ms	remaining: 15.7ms
25:	learn: 0.8499299	total: 16.3ms	remaining: 15.1ms
26:	learn: 0.8499299	total: 17ms	remaining: 14.5ms
27:	learn: 0.8457223	total: 17.6ms	remaining: 13.8ms
28:	learn: 0.8471248	total: 18.3ms	remaining: 13.2ms
29:	learn: 0.8485273	total: 18.9ms	remaining: 12.6ms
30:	learn: 0.8485273	total: 19.6ms	remaining: 12ms
31:	learn: 0.8513324	total: 20.2ms	remaining: 11.4ms
32:	learn: 0.8527349	total: 20.9ms	remaining: 10.8ms
33:	learn: 0.8555400	total: 21.5ms	remaining: 10.1ms
34:	learn: 0.8555400	total: 22.2ms	remaining: 9.51ms
35:	learn: 0.8541374	total: 22.6ms	remaining: 8.78ms
36:	learn: 0.8569425	total: 23.2ms	remaining: 8.16ms
37:	learn: 0.8653576	total: 23.9ms	remaining: 7.54ms
38:	learn: 0.8611501	total: 24.6ms	remaining: 6.93ms
39:	learn: 0.8583450	total: 24.9ms	remaining: 6.22ms
40:	learn: 0.8583450	total: 25.6ms	remaining: 5.62ms
41:	learn: 0.8611501	total: 26.3ms	remaining: 5.01ms
42:	learn: 0.8625526	total: 27ms	remaining: 4.39ms
43:	learn: 0.8639551	total: 27.7ms	remaining: 3.77ms
Learning rate set to 0.222036
0:	learn: 0.8244382	total: 47.8ms	remaining: 1.39s
1:	learn: 0.8230337	total: 49.3ms	remaining: 690ms
2:	learn: 0.8230337	total: 49.9ms	remaining: 449ms
3:	learn: 0.8244382	total: 50.6ms	remaining: 329ms
4:	learn: 0.8328652	total: 51.5ms	remaining: 258ms
5:	learn: 0.8342697	total: 52.1ms	remaining: 209ms
6:	learn: 0.8314607	total: 52.9ms	remaining: 174ms
7:	learn: 0.8398876	total: 53.6ms	remaining: 147ms
8:	learn: 0.8258427	total: 53.7ms	remaining: 125ms
9:	learn: 0.8300562	total: 54.4ms	remaining: 109ms
10:	learn: 0.8356742	total: 55.2ms	remaining: 95.4ms
11:	learn: 0.8384831	total: 55.9ms	remaining: 83.9ms
12:	learn: 0.8384831	total: 56.6ms	remaining: 74ms
13:	learn: 0.8356742	total: 57.2ms	remaining: 65.4ms
14:	learn: 0.8356742	total: 57.5ms	remaining: 57.5ms
15:	learn: 0.8384831	total: 58.2ms	remaining: 50.9ms
16:	learn: 0.8412921	total: 58.9ms	remaining: 45ms
17:	learn: 0.8384831	total: 59.5ms	remaining: 39.7ms
18:	learn: 0.8412921	total: 60.1ms	remaining: 34.8ms
19:	learn: 0.8398876	total: 60.8ms	remaining: 30.4ms
20:	learn: 0.8455056	total: 61.5ms	remaining: 26.4ms
21:	learn: 0.8441011	total: 62.2ms	remaining: 22.6ms
22:	learn: 0.8441011	total: 62.9ms	remaining: 19.1ms
23:	learn: 0.8426966	total: 63.6ms	remaining: 15.9ms
24:	learn: 0.8483146	total: 64.2ms	remaining: 12.8ms
25:	learn: 0.8511236	total: 64.9ms	remaining: 9.99ms
26:	learn: 0.8553371	total: 65.6ms	remaining: 7.29ms
27:	learn: 0.8525281	total: 66.3ms	remaining: 4.74ms
28:	learn: 0.8553371	total: 67.1ms	remaining: 2.31ms
29:	learn: 0.8539326	total: 67.7ms	remaining: 0us
Learning rate set to 0.170653
0:	learn: 0.7826087	total: 388us	remaining: 15.2ms
1:	learn: 0.8106592	total: 1.12ms	remaining: 21.3ms
2:	learn: 0.8204769	total: 1.85ms	remaining: 22.8ms
3:	learn: 0.8288920	total: 2.56ms	remaining: 23ms
4:	learn: 0.8302945	total: 3.26ms	remaining: 22.8ms
5:	learn: 0.8288920	total: 4.07ms	remaining: 23ms
6:	learn: 0.8302945	total: 4.35ms	remaining: 20.5ms
7:	learn: 0.8330996	total: 5.07ms	remaining: 20.3ms
8:	learn: 0.8345021	total: 5.82ms	remaining: 20ms
9:	learn: 0.8373072	total: 6.54ms	remaining: 19.6ms
10:	learn: 0.8330996	total: 7.28ms	remaining: 19.2ms
11:	learn: 0.8443198	total: 7.99ms	remaining: 18.6ms
12:	learn: 0.8429173	total: 8.69ms	remaining: 18.1ms
13:	learn: 0.8387097	total: 9.39ms	remaining: 17.4ms
14:	learn: 0.8401122	total: 9.68ms	remaining: 16.1ms
15:	learn: 0.8373072	total: 10.5ms	remaining: 15.8ms
16:	learn: 0.8359046	total: 11.2ms	remaining: 15.2ms
17:	learn: 0.8373072	total: 11.9ms	remaining: 14.5ms
18:	learn: 0.8387097	total: 12.6ms	remaining: 13.9ms
19:	learn: 0.8401122	total: 14.1ms	remaining: 14.1ms
20:	learn: 0.8457223	total: 14.7ms	remaining: 13.3ms
21:	learn: 0.8457223	total: 15.4ms	remaining: 12.6ms
22:	learn: 0.8401122	total: 16.1ms	remaining: 11.9ms
23:	learn: 0.8443198	total: 16.8ms	remaining: 11.2ms
24:	learn: 0.8429173	total: 17.4ms	remaining: 10.5ms
25:	learn: 0.8457223	total: 18.1ms	remaining: 9.74ms
26:	learn: 0.8471248	total: 18.4ms	remaining: 8.85ms
27:	learn: 0.8499299	total: 19ms	remaining: 8.15ms
28:	learn: 0.8569425	total: 19.7ms	remaining: 7.47ms
29:	learn: 0.8597475	total: 20.4ms	remaining: 6.8ms
30:	learn: 0.8583450	total: 21.1ms	remaining: 6.13ms
31:	learn: 0.8625526	total: 21.8ms	remaining: 5.45ms
32:	learn: 0.8583450	total: 22.5ms	remaining: 4.77ms
33:	learn: 0.8597475	total: 23.2ms	remaining: 4.09ms
34:	learn: 0.8597475	total: 23.9ms	remaining: 3.41ms
35:	learn: 0.8597475	total: 24.6ms	remaining: 2.73ms
36:	learn: 0.8611501	total: 25.3ms	remaining: 2.05ms
37:	learn: 0.8597475	total: 25.6ms	remaining: 1.35ms
38:	learn: 0.8625526	total: 26.4ms	remaining: 675us
39:	learn: 0.8611501	total: 27.1ms	remaining: 0us
Learning rate set to 0.138991
0:	learn: 0.8244382	total: 729us	remaining: 35.8ms
1:	learn: 0.8230337	total: 1.44ms	remaining: 34.5ms
2:	learn: 0.8230337	total: 2.11ms	remaining: 33.1ms
3:	learn: 0.8244382	total: 2.85ms	remaining: 32.7ms
4:	learn: 0.8258427	total: 3.51ms	remaining: 31.6ms
5:	learn: 0.8272472	total: 4.16ms	remaining: 30.5ms
6:	learn: 0.8272472	total: 4.8ms	remaining: 29.5ms
7:	learn: 0.8286517	total: 5.48ms	remaining: 28.8ms
8:	learn: 0.8258427	total: 5.63ms	remaining: 25.6ms
9:	learn: 0.8300562	total: 6.34ms	remaining: 25.4ms
10:	learn: 0.8314607	total: 6.99ms	remaining: 24.8ms
11:	learn: 0.8314607	total: 7.68ms	remaining: 24.3ms
12:	learn: 0.8314607	total: 8.11ms	remaining: 23.1ms
13:	learn: 0.8314607	total: 8.75ms	remaining: 22.5ms
14:	learn: 0.8314607	total: 9.39ms	remaining: 21.9ms
15:	learn: 0.8356742	total: 10.1ms	remaining: 21.4ms
16:	learn: 0.8356742	total: 10.7ms	remaining: 20.8ms
17:	learn: 0.8314607	total: 11.4ms	remaining: 20.2ms
18:	learn: 0.8328652	total: 12ms	remaining: 19.6ms
19:	learn: 0.8342697	total: 12.7ms	remaining: 19ms
20:	learn: 0.8426966	total: 13.4ms	remaining: 18.4ms
21:	learn: 0.8441011	total: 14ms	remaining: 17.9ms
22:	learn: 0.8483146	total: 14.7ms	remaining: 17.3ms
23:	learn: 0.8441011	total: 15.4ms	remaining: 16.7ms
24:	learn: 0.8426966	total: 16.1ms	remaining: 16.1ms
25:	learn: 0.8483146	total: 16.7ms	remaining: 15.4ms
26:	learn: 0.8455056	total: 17.4ms	remaining: 14.8ms
27:	learn: 0.8441011	total: 18ms	remaining: 14.2ms
28:	learn: 0.8441011	total: 18.7ms	remaining: 13.5ms
29:	learn: 0.8483146	total: 19.3ms	remaining: 12.9ms
30:	learn: 0.8469101	total: 19.9ms	remaining: 12.2ms
31:	learn: 0.8469101	total: 20.5ms	remaining: 11.6ms
32:	learn: 0.8455056	total: 21.2ms	remaining: 10.9ms
33:	learn: 0.8483146	total: 21.8ms	remaining: 10.3ms
34:	learn: 0.8483146	total: 22.4ms	remaining: 9.59ms
35:	learn: 0.8497191	total: 23ms	remaining: 8.95ms
36:	learn: 0.8497191	total: 23.2ms	remaining: 8.15ms
37:	learn: 0.8469101	total: 23.9ms	remaining: 7.54ms
38:	learn: 0.8469101	total: 24.3ms	remaining: 6.85ms
39:	learn: 0.8511236	total: 24.9ms	remaining: 6.24ms
40:	learn: 0.8553371	total: 25.6ms	remaining: 5.63ms
41:	learn: 0.8567416	total: 26.5ms	remaining: 5.05ms
42:	learn: 0.8567416	total: 27.2ms	remaining: 4.42ms
43:	learn: 0.8553371	total: 27.9ms	remaining: 3.8ms
44:	learn: 0.8553371	total: 28.6ms	remaining: 3.17ms
45:	learn: 0.8581461	total: 29.3ms	remaining: 2.54ms
46:	learn: 0.8581461	total: 29.9ms	remaining: 1.91ms
47:	learn: 0.8623596	total: 30.6ms	remaining: 1.27ms
48:	learn: 0.8651685	total: 31.3ms	remaining: 638us
49:	learn: 0.8609551	total: 32ms	remaining: 0us
Learning rate set to 0.139075
0:	learn: 0.8176718	total: 749us	remaining: 36.7ms
1:	learn: 0.8176718	total: 1.45ms	remaining: 34.8ms
2:	learn: 0.8190743	total: 2.11ms	remaining: 33.1ms
3:	learn: 0.8204769	total: 2.78ms	remaining: 32ms
4:	learn: 0.8176718	total: 3.41ms	remaining: 30.7ms
5:	learn: 0.8176718	total: 4.04ms	remaining: 29.6ms
6:	learn: 0.8190743	total: 4.66ms	remaining: 28.6ms
7:	learn: 0.8162693	total: 5.3ms	remaining: 27.8ms
8:	learn: 0.8218794	total: 5.45ms	remaining: 24.8ms
9:	learn: 0.8246844	total: 6.1ms	remaining: 24.4ms
10:	learn: 0.8260870	total: 6.73ms	remaining: 23.9ms
11:	learn: 0.8274895	total: 7.37ms	remaining: 23.3ms
12:	learn: 0.8274895	total: 8ms	remaining: 22.8ms
13:	learn: 0.8260870	total: 8.64ms	remaining: 22.2ms
14:	learn: 0.8288920	total: 9.29ms	remaining: 21.7ms
15:	learn: 0.8302945	total: 9.98ms	remaining: 21.2ms
16:	learn: 0.8260870	total: 10.6ms	remaining: 20.6ms
17:	learn: 0.8274895	total: 11.3ms	remaining: 20.1ms
18:	learn: 0.8246844	total: 11.9ms	remaining: 19.5ms
19:	learn: 0.8246844	total: 12.6ms	remaining: 18.9ms
20:	learn: 0.8260870	total: 13.2ms	remaining: 18.3ms
21:	learn: 0.8260870	total: 13.9ms	remaining: 17.7ms
22:	learn: 0.8288920	total: 14.5ms	remaining: 17ms
23:	learn: 0.8288920	total: 14.9ms	remaining: 16.2ms
24:	learn: 0.8288920	total: 15.6ms	remaining: 15.6ms
25:	learn: 0.8302945	total: 16.3ms	remaining: 15.1ms
26:	learn: 0.8330996	total: 17ms	remaining: 14.5ms
27:	learn: 0.8316971	total: 17.7ms	remaining: 13.9ms
28:	learn: 0.8316971	total: 18.3ms	remaining: 13.3ms
29:	learn: 0.8316971	total: 18.9ms	remaining: 12.6ms
30:	learn: 0.8359046	total: 19.6ms	remaining: 12ms
31:	learn: 0.8345021	total: 20ms	remaining: 11.3ms
32:	learn: 0.8345021	total: 20.7ms	remaining: 10.7ms
33:	learn: 0.8345021	total: 21.4ms	remaining: 10.1ms
Learning rate set to 0.24435
0:	learn: 0.8237935	total: 47.6ms	remaining: 1.38s
1:	learn: 0.8204265	total: 48.3ms	remaining: 677ms
2:	learn: 0.8226712	total: 49.8ms	remaining: 449ms
3:	learn: 0.8237935	total: 50.7ms	remaining: 329ms
4:	learn: 0.8249158	total: 51.5ms	remaining: 257ms
5:	learn: 0.8249158	total: 52.2ms	remaining: 209ms
6:	learn: 0.8260382	total: 53ms	remaining: 174ms
7:	learn: 0.8249158	total: 53.8ms	remaining: 148ms
8:	learn: 0.8271605	total: 54ms	remaining: 126ms
9:	learn: 0.8282828	total: 54.8ms	remaining: 110ms
10:	learn: 0.8305275	total: 55.6ms	remaining: 96ms
11:	learn: 0.8327722	total: 56.3ms	remaining: 84.5ms
12:	learn: 0.8316498	total: 57.1ms	remaining: 74.6ms
13:	learn: 0.8316498	total: 57.8ms	remaining: 66ms
14:	learn: 0.8316498	total: 58.1ms	remaining: 58.1ms
15:	learn: 0.8338945	total: 58.9ms	remaining: 51.5ms
16:	learn: 0.8372615	total: 59.6ms	remaining: 45.6ms
17:	learn: 0.8383838	total: 60.4ms	remaining: 40.3ms
18:	learn: 0.8338945	total: 61.8ms	remaining: 35.8ms
19:	learn: 0.8338945	total: 63.2ms	remaining: 31.6ms
20:	learn: 0.8372615	total: 63.9ms	remaining: 27.4ms
21:	learn: 0.8372615	total: 64.7ms	remaining: 23.5ms
22:	learn: 0.8439955	total: 65.4ms	remaining: 19.9ms
23:	learn: 0.8451178	total: 66.1ms	remaining: 16.5ms
24:	learn: 0.8484848	total: 66.9ms	remaining: 13.4ms
25:	learn: 0.8507295	total: 67.6ms	remaining: 10.4ms
26:	learn: 0.8518519	total: 68.4ms	remaining: 7.6ms
27:	learn: 0.8507295	total: 69.1ms	remaining: 4.94ms
28:	learn: 0.8507295	total: 69.4ms	remaining: 2.39ms
29:	learn: 0.8518519	total: 70.3ms	remaining: 0us
{'iterations': 30, 'use_best_model': False} 0.8698024835274067
[0.86980248 0.86918843 0.86878172]
**************
TIME USED (ms): 1624550.681

In [35]:
orig_data=pd.read_csv('/opt/neurothink/neuro-deb05933716f4eb6be138022abf35d2f/train.csv')
orig_data.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [36]:
for col in orig_data:
    orig_data[col] = orig_data[col].fillna('NaN')
train_X = orig_data.loc[:, orig_data.columns!='Survived']
train_Y = orig_data['Survived']
train_X.head()

,PassengerId,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

In [37]:
categorical_indices = [0,1,2,3,5,6,7,9,10]
start = time.time_ns()
gs_cat = GridSearchCV(estimator = cat, param_grid = param_test, scoring='roc_auc',n_jobs=-1,cv=5)
gs_cat.fit(train_X,train_Y, cat_features=categorical_indices)
end = time.time_ns()
print(gs_cat.best_params_,gs_cat.best_score_)
print(gs_cat.cv_results_['mean_test_score'])
print('**************')
print('TIME USED (ms):', (end-start)/1000)

Learning rate set to 0.222169
0:	learn: 0.8274895	total: 47.7ms	remaining: 1.38s
1:	learn: 0.8162693	total: 48.7ms	remaining: 682ms
2:	learn: 0.8106592	total: 49.3ms	remaining: 443ms
3:	learn: 0.8274895	total: 49.8ms	remaining: 324ms
4:	learn: 0.8288920	total: 50.7ms	remaining: 253ms
5:	learn: 0.8302945	total: 51.3ms	remaining: 205ms
6:	learn: 0.8316971	total: 51.8ms	remaining: 170ms
7:	learn: 0.8373072	total: 52.4ms	remaining: 144ms
8:	learn: 0.8330996	total: 52.6ms	remaining: 123ms
9:	learn: 0.8359046	total: 53.2ms	remaining: 106ms
10:	learn: 0.8359046	total: 53.7ms	remaining: 92.7ms
11:	learn: 0.8429173	total: 54.2ms	remaining: 81.3ms
12:	learn: 0.8429173	total: 55ms	remaining: 71.9ms
13:	learn: 0.8457223	total: 55.5ms	remaining: 63.4ms
14:	learn: 0.8457223	total: 55.7ms	remaining: 55.7ms
15:	learn: 0.8457223	total: 56.2ms	remaining: 49.2ms
16:	learn: 0.8429173	total: 56.8ms	remaining: 43.4ms
17:	learn: 0.8457223	total: 57.3ms	remaining: 38.2ms
18:	learn: 0.8443198	total: 57.9ms	remaining: 33.5ms
19:	learn: 0.8443198	total: 58.4ms	remaining: 29.2ms
20:	learn: 0.8429173	total: 59ms	remaining: 25.3ms
21:	learn: 0.8471248	total: 59.5ms	remaining: 21.6ms
22:	learn: 0.8443198	total: 60.1ms	remaining: 18.3ms
23:	learn: 0.8429173	total: 60.6ms	remaining: 15.1ms
24:	learn: 0.8457223	total: 61.1ms	remaining: 12.2ms
25:	learn: 0.8471248	total: 61.7ms	remaining: 9.49ms
26:	learn: 0.8457223	total: 62.2ms	remaining: 6.92ms
27:	learn: 0.8499299	total: 62.8ms	remaining: 4.49ms
28:	learn: 0.8471248	total: 63.4ms	remaining: 2.19ms
29:	learn: 0.8499299	total: 63.9ms	remaining: 0us
Learning rate set to 0.222169
0:	learn: 0.8176718	total: 727us	remaining: 21.1ms
1:	learn: 0.8176718	total: 1.33ms	remaining: 18.6ms
2:	learn: 0.8162693	total: 1.96ms	remaining: 17.6ms
3:	learn: 0.8232819	total: 2.55ms	remaining: 16.6ms
4:	learn: 0.8176718	total: 3.09ms	remaining: 15.4ms
5:	learn: 0.8204769	total: 3.63ms	remaining: 14.5ms
6:	learn: 0.8232819	total: 4.17ms	remaining: 13.7ms
7:	learn: 0.8288920	total: 4.73ms	remaining: 13ms
8:	learn: 0.8274895	total: 4.84ms	remaining: 11.3ms
9:	learn: 0.8246844	total: 5.39ms	remaining: 10.8ms
10:	learn: 0.8218794	total: 5.94ms	remaining: 10.3ms
11:	learn: 0.8316971	total: 6.51ms	remaining: 9.76ms
12:	learn: 0.8274895	total: 7.05ms	remaining: 9.22ms
13:	learn: 0.8302945	total: 7.6ms	remaining: 8.69ms
14:	learn: 0.8302945	total: 7.82ms	remaining: 7.82ms
15:	learn: 0.8302945	total: 8.39ms	remaining: 7.34ms
16:	learn: 0.8345021	total: 8.96ms	remaining: 6.85ms
17:	learn: 0.8316971	total: 9.53ms	remaining: 6.35ms
18:	learn: 0.8330996	total: 10.1ms	remaining: 5.88ms
19:	learn: 0.8330996	total: 10.8ms	remaining: 5.39ms
20:	learn: 0.8415147	total: 11.4ms	remaining: 4.89ms
21:	learn: 0.8429173	total: 12ms	remaining: 4.38ms
22:	learn: 0.8471248	total: 12.7ms	remaining: 3.86ms
23:	learn: 0.8485273	total: 13.3ms	remaining: 3.32ms
24:	learn: 0.8471248	total: 13.9ms	remaining: 2.78ms
25:	learn: 0.8499299	total: 14.5ms	remaining: 2.23ms
26:	learn: 0.8569425	total: 15.1ms	remaining: 1.68ms
27:	learn: 0.8555400	total: 15.7ms	remaining: 1.12ms
28:	learn: 0.8597475	total: 16.3ms	remaining: 560us
29:	learn: 0.8611501	total: 16.8ms	remaining: 0us
Learning rate set to 0.170653
0:	learn: 0.8274895	total: 642us	remaining: 25.1ms
1:	learn: 0.8162693	total: 880us	remaining: 16.7ms
2:	learn: 0.8106592	total: 1.49ms	remaining: 18.4ms
3:	learn: 0.8274895	total: 2.1ms	remaining: 18.9ms
4:	learn: 0.8316971	total: 2.7ms	remaining: 18.9ms
5:	learn: 0.8288920	total: 3.3ms	remaining: 18.7ms
6:	learn: 0.8316971	total: 3.89ms	remaining: 18.4ms
7:	learn: 0.8359046	total: 4.54ms	remaining: 18.2ms
8:	learn: 0.8359046	total: 4.79ms	remaining: 16.5ms
9:	learn: 0.8373072	total: 5.41ms	remaining: 16.2ms
10:	learn: 0.8401122	total: 6.04ms	remaining: 15.9ms
11:	learn: 0.8415147	total: 6.63ms	remaining: 15.5ms
12:	learn: 0.8373072	total: 7.24ms	remaining: 15ms
13:	learn: 0.8387097	total: 7.86ms	remaining: 14.6ms
14:	learn: 0.8387097	total: 8.1ms	remaining: 13.5ms
15:	learn: 0.8387097	total: 8.68ms	remaining: 13ms
16:	learn: 0.8387097	total: 9.25ms	remaining: 12.5ms
17:	learn: 0.8387097	total: 9.84ms	remaining: 12ms
18:	learn: 0.8359046	total: 10.4ms	remaining: 11.5ms
19:	learn: 0.8387097	total: 11.1ms	remaining: 11.1ms
20:	learn: 0.8443198	total: 11.6ms	remaining: 10.5ms
21:	learn: 0.8429173	total: 12.2ms	remaining: 9.98ms
22:	learn: 0.8415147	total: 12.8ms	remaining: 9.44ms
23:	learn: 0.8429173	total: 13.3ms	remaining: 8.88ms
24:	learn: 0.8471248	total: 13.9ms	remaining: 8.33ms
25:	learn: 0.8457223	total: 14.4ms	remaining: 7.78ms
26:	learn: 0.8457223	total: 15ms	remaining: 7.24ms
27:	learn: 0.8457223	total: 15.6ms	remaining: 6.67ms
28:	learn: 0.8485273	total: 16.1ms	remaining: 6.11ms
29:	learn: 0.8541374	total: 16.7ms	remaining: 5.55ms
30:	learn: 0.8513324	total: 17.2ms	remaining: 4.99ms
31:	learn: 0.8541374	total: 17.7ms	remaining: 4.43ms
32:	learn: 0.8527349	total: 18.3ms	remaining: 3.88ms
33:	learn: 0.8569425	total: 18.9ms	remaining: 3.33ms
34:	learn: 0.8569425	total: 19.4ms	remaining: 2.77ms
35:	learn: 0.8569425	total: 19.7ms	remaining: 2.19ms
36:	learn: 0.8597475	total: 20.2ms	remaining: 1.64ms
37:	learn: 0.8555400	total: 20.8ms	remaining: 1.09ms
38:	learn: 0.8555400	total: 21.3ms	remaining: 547us
39:	learn: 0.8583450	total: 21.9ms	remaining: 0us
Learning rate set to 0.139075
0:	learn: 0.8246844	total: 626us	remaining: 30.7ms
1:	learn: 0.8134642	total: 861us	remaining: 20.7ms
2:	learn: 0.8064516	total: 1.4ms	remaining: 21.9ms
3:	learn: 0.8218794	total: 1.97ms	remaining: 22.7ms
4:	learn: 0.8162693	total: 2.55ms	remaining: 22.9ms
5:	learn: 0.8204769	total: 3.1ms	remaining: 22.8ms
6:	learn: 0.8246844	total: 3.67ms	remaining: 22.6ms
7:	learn: 0.8204769	total: 4.25ms	remaining: 22.3ms
8:	learn: 0.8204769	total: 4.47ms	remaining: 20.3ms
9:	learn: 0.8218794	total: 5.03ms	remaining: 20.1ms
10:	learn: 0.8274895	total: 5.57ms	remaining: 19.7ms
11:	learn: 0.8232819	total: 6.11ms	remaining: 19.4ms
12:	learn: 0.8316971	total: 6.67ms	remaining: 19ms
13:	learn: 0.8345021	total: 7.24ms	remaining: 18.6ms
14:	learn: 0.8288920	total: 7.46ms	remaining: 17.4ms
15:	learn: 0.8260870	total: 8.02ms	remaining: 17.1ms
16:	learn: 0.8232819	total: 8.59ms	remaining: 16.7ms
17:	learn: 0.8345021	total: 9.15ms	remaining: 16.3ms
18:	learn: 0.8359046	total: 9.72ms	remaining: 15.9ms
19:	learn: 0.8359046	total: 10.3ms	remaining: 15.4ms
20:	learn: 0.8345021	total: 10.9ms	remaining: 15.1ms
21:	learn: 0.8387097	total: 11.5ms	remaining: 14.6ms
22:	learn: 0.8401122	total: 12ms	remaining: 14.1ms
23:	learn: 0.8387097	total: 12.7ms	remaining: 13.7ms
24:	learn: 0.8373072	total: 13.2ms	remaining: 13.2ms
25:	learn: 0.8373072	total: 13.8ms	remaining: 12.7ms
26:	learn: 0.8373072	total: 14.4ms	remaining: 12.2ms
27:	learn: 0.8359046	total: 14.9ms	remaining: 11.7ms
28:	learn: 0.8387097	total: 15.4ms	remaining: 11.2ms
29:	learn: 0.8387097	total: 16ms	remaining: 10.6ms
30:	learn: 0.8373072	total: 16.5ms	remaining: 10.1ms
31:	learn: 0.8387097	total: 17ms	remaining: 9.57ms
32:	learn: 0.8387097	total: 17.5ms	remaining: 9.04ms
33:	learn: 0.8387097	total: 18.1ms	remaining: 8.5ms
34:	learn: 0.8373072	total: 18.2ms	remaining: 7.81ms
35:	learn: 0.8373072	total: 18.8ms	remaining: 7.3ms
36:	learn: 0.8359046	total: 19.3ms	remaining: 6.78ms
37:	learn: 0.8373072	total: 19.6ms	remaining: 6.19ms
38:	learn: 0.8387097	total: 20.1ms	remaining: 5.68ms
39:	learn: 0.8401122	total: 20.6ms	remaining: 5.16ms
40:	learn: 0.8401122	total: 21.2ms	remaining: 4.65ms
41:	learn: 0.8429173	total: 21.7ms	remaining: 4.13ms
42:	learn: 0.8429173	total: 22.3ms	remaining: 3.63ms
43:	learn: 0.8429173	total: 22.8ms	remaining: 3.11ms
44:	learn: 0.8429173	total: 23.4ms	remaining: 2.6ms
45:	learn: 0.8415147	total: 23.9ms	remaining: 2.08ms
46:	learn: 0.8457223	total: 24.4ms	remaining: 1.56ms
47:	learn: 0.8471248	total: 25ms	remaining: 1.04ms
48:	learn: 0.8471248	total: 25.5ms	remaining: 520us
49:	learn: 0.8471248	total: 26ms	remaining: 0us
Learning rate set to 0.222169
0:	learn: 0.8050491	total: 2.55ms	remaining: 73.9ms
1:	learn: 0.8036466	total: 3.5ms	remaining: 49.1ms
2:	learn: 0.8036466	total: 4.16ms	remaining: 37.4ms
Learning rate set to 0.222169
0:	learn: 0.8246844	total: 48.7ms	remaining: 1.41s
1:	learn: 0.8134642	total: 49.7ms	remaining: 695ms
2:	learn: 0.8036466	total: 51.1ms	remaining: 460ms
3:	learn: 0.8176718	total: 51.8ms	remaining: 337ms
4:	learn: 0.8190743	total: 52.5ms	remaining: 263ms
5:	learn: 0.8232819	total: 53.2ms	remaining: 213ms
6:	learn: 0.8316971	total: 53.9ms	remaining: 177ms
7:	learn: 0.8260870	total: 54.6ms	remaining: 150ms
8:	learn: 0.8274895	total: 54.9ms	remaining: 128ms
9:	learn: 0.8330996	total: 55.6ms	remaining: 111ms
10:	learn: 0.8330996	total: 56.3ms	remaining: 97.3ms
11:	learn: 0.8330996	total: 57ms	remaining: 85.5ms
12:	learn: 0.8330996	total: 57.7ms	remaining: 75.4ms
13:	learn: 0.8345021	total: 58.4ms	remaining: 66.8ms
14:	learn: 0.8373072	total: 58.7ms	remaining: 58.7ms
15:	learn: 0.8373072	total: 60.1ms	remaining: 52.6ms
16:	learn: 0.8345021	total: 60.8ms	remaining: 46.5ms
17:	learn: 0.8359046	total: 61.6ms	remaining: 41.1ms
18:	learn: 0.8401122	total: 62.3ms	remaining: 36.1ms
19:	learn: 0.8387097	total: 63ms	remaining: 31.5ms
20:	learn: 0.8415147	total: 63.7ms	remaining: 27.3ms
21:	learn: 0.8415147	total: 64.5ms	remaining: 23.4ms
22:	learn: 0.8443198	total: 65.2ms	remaining: 19.9ms
23:	learn: 0.8471248	total: 66ms	remaining: 16.5ms
24:	learn: 0.8429173	total: 66.7ms	remaining: 13.3ms
25:	learn: 0.8471248	total: 67.4ms	remaining: 10.4ms
26:	learn: 0.8485273	total: 68ms	remaining: 7.56ms
27:	learn: 0.8499299	total: 68.7ms	remaining: 4.91ms
28:	learn: 0.8499299	total: 69.4ms	remaining: 2.39ms
29:	learn: 0.8485273	total: 70.1ms	remaining: 0us
Learning rate set to 0.170653
0:	learn: 0.8246844	total: 804us	remaining: 31.4ms
1:	learn: 0.8134642	total: 1.15ms	remaining: 21.8ms
2:	learn: 0.8050491	total: 1.92ms	remaining: 23.7ms
3:	learn: 0.8148668	total: 2.62ms	remaining: 23.5ms
4:	learn: 0.8162693	total: 3.33ms	remaining: 23.3ms
5:	learn: 0.8176718	total: 4.08ms	remaining: 23.1ms
6:	learn: 0.8190743	total: 4.88ms	remaining: 23ms
7:	learn: 0.8204769	total: 5.65ms	remaining: 22.6ms
8:	learn: 0.8190743	total: 5.97ms	remaining: 20.6ms
9:	learn: 0.8246844	total: 6.7ms	remaining: 20.1ms
10:	learn: 0.8204769	total: 7.43ms	remaining: 19.6ms
11:	learn: 0.8274895	total: 8.3ms	remaining: 19.4ms
12:	learn: 0.8373072	total: 9.01ms	remaining: 18.7ms
13:	learn: 0.8359046	total: 9.7ms	remaining: 18ms
14:	learn: 0.8316971	total: 9.99ms	remaining: 16.6ms
15:	learn: 0.8359046	total: 10.7ms	remaining: 16.1ms
16:	learn: 0.8316971	total: 11.4ms	remaining: 15.5ms
17:	learn: 0.8345021	total: 12.2ms	remaining: 14.9ms
18:	learn: 0.8345021	total: 12.9ms	remaining: 14.3ms
19:	learn: 0.8387097	total: 13.6ms	remaining: 13.6ms
20:	learn: 0.8373072	total: 14.7ms	remaining: 13.3ms
21:	learn: 0.8401122	total: 15.5ms	remaining: 12.7ms
22:	learn: 0.8359046	total: 16.2ms	remaining: 12ms
23:	learn: 0.8373072	total: 17ms	remaining: 11.3ms
24:	learn: 0.8387097	total: 17.7ms	remaining: 10.6ms
25:	learn: 0.8387097	total: 18.4ms	remaining: 9.91ms
26:	learn: 0.8373072	total: 19.2ms	remaining: 9.24ms
27:	learn: 0.8401122	total: 19.9ms	remaining: 8.53ms
28:	learn: 0.8401122	total: 20.6ms	remaining: 7.81ms
29:	learn: 0.8373072	total: 21.3ms	remaining: 7.11ms
30:	learn: 0.8373072	total: 22.1ms	remaining: 6.41ms
31:	learn: 0.8359046	total: 22.8ms	remaining: 5.69ms
32:	learn: 0.8387097	total: 23.5ms	remaining: 4.99ms
33:	learn: 0.8457223	total: 24.2ms	remaining: 4.28ms
34:	learn: 0.8457223	total: 25ms	remaining: 3.57ms
35:	learn: 0.8457223	total: 25.8ms	remaining: 2.86ms
36:	learn: 0.8457223	total: 26.6ms	remaining: 2.15ms
37:	learn: 0.8471248	total: 27.3ms	remaining: 1.44ms
38:	learn: 0.8471248	total: 28.1ms	remaining: 719us
39:	learn: 0.8471248	total: 28.8ms	remaining: 0us
Learning rate set to 0.139075
0:	learn: 0.7826087	total: 347us	remaining: 17ms
1:	learn: 0.8106592	total: 1.04ms	remaining: 25ms
2:	learn: 0.8204769	total: 1.75ms	remaining: 27.4ms
3:	learn: 0.8288920	total: 2.43ms	remaining: 28ms
4:	learn: 0.8288920	total: 3.16ms	remaining: 28.5ms
5:	learn: 0.8316971	total: 3.86ms	remaining: 28.3ms
6:	learn: 0.8316971	total: 4.17ms	remaining: 25.6ms
7:	learn: 0.8345021	total: 4.89ms	remaining: 25.7ms
8:	learn: 0.8330996	total: 5.6ms	remaining: 25.5ms
9:	learn: 0.8330996	total: 6.3ms	remaining: 25.2ms
10:	learn: 0.8345021	total: 7ms	remaining: 24.8ms
11:	learn: 0.8316971	total: 7.3ms	remaining: 23.1ms
12:	learn: 0.8373072	total: 7.99ms	remaining: 22.8ms
13:	learn: 0.8401122	total: 8.71ms	remaining: 22.4ms
14:	learn: 0.8401122	total: 9.41ms	remaining: 22ms
15:	learn: 0.8330996	total: 10.1ms	remaining: 21.4ms
16:	learn: 0.8359046	total: 10.8ms	remaining: 20.9ms
17:	learn: 0.8373072	total: 11.5ms	remaining: 20.4ms
18:	learn: 0.8359046	total: 12.2ms	remaining: 19.9ms
19:	learn: 0.8359046	total: 12.9ms	remaining: 19.3ms
20:	learn: 0.8345021	total: 13.5ms	remaining: 18.7ms
21:	learn: 0.8387097	total: 14.2ms	remaining: 18ms
22:	learn: 0.8373072	total: 14.9ms	remaining: 17.5ms
23:	learn: 0.8359046	total: 15.5ms	remaining: 16.8ms
24:	learn: 0.8387097	total: 16.2ms	remaining: 16.2ms
25:	learn: 0.8373072	total: 16.9ms	remaining: 15.6ms
26:	learn: 0.8373072	total: 17.5ms	remaining: 14.9ms
27:	learn: 0.8415147	total: 18.2ms	remaining: 14.3ms
28:	learn: 0.8415147	total: 18.9ms	remaining: 13.7ms
29:	learn: 0.8429173	total: 19.5ms	remaining: 13ms
30:	learn: 0.8471248	total: 20.2ms	remaining: 12.4ms
31:	learn: 0.8513324	total: 20.9ms	remaining: 11.8ms
32:	learn: 0.8485273	total: 21.6ms	remaining: 11.1ms
33:	learn: 0.8527349	total: 22.3ms	remaining: 10.5ms
34:	learn: 0.8611501	total: 23ms	remaining: 9.84ms
35:	learn: 0.8541374	total: 23.9ms	remaining: 9.29ms
36:	learn: 0.8597475	total: 24.6ms	remaining: 8.64ms
37:	learn: 0.8583450	total: 25.3ms	remaining: 7.99ms
38:	learn: 0.8583450	total: 26.1ms	remaining: 7.36ms
39:	learn: 0.8583450	total: 26.8ms	remaining: 6.7ms
40:	learn: 0.8597475	total: 27.5ms	remaining: 6.04ms
41:	learn: 0.8583450	total: 28.2ms	remaining: 5.37ms
42:	learn: 0.8611501	total: 28.9ms	remaining: 4.71ms
43:	learn: 0.8611501	total: 29.6ms	remaining: 4.04ms
44:	learn: 0.8611501	total: 30.1ms	remaining: 3.35ms
45:	learn: 0.8597475	total: 30.8ms	remaining: 2.68ms
46:	learn: 0.8625526	total: 31.6ms	remaining: 2.02ms
47:	learn: 0.8611501	total: 32.2ms	remaining: 1.34ms
48:	learn: 0.8583450	total: 32.5ms	remaining: 663us
49:	learn: 0.8583450	total: 33.2ms	remaining: 0us
Learning rate set to 0.222036
0:	learn: 0.8075843	total: 2.85ms	remaining: 82.8ms
1:	learn: 0.8132022	total: 4.96ms	remaining: 69.5ms
2:	learn: 0.8132022	total: 7.44ms	remaining: 66.9ms
3:	learn: 0.8103933	total: 8.5ms	remaining: 55.3ms
4:	learn: 0.8244382	total: 10.3ms	remaining: 51.6ms
5:	learn: 0.8174157	total: 10.9ms	remaining: 43.7ms
6:	learn: 0.8174157	total: 11.3ms	remaining: 37.1ms
7:	learn: 0.8174157	total: 12.4ms	remaining: 34ms
8:	learn: 0.8202247	total: 12.8ms	remaining: 29.8ms
9:	learn: 0.8230337	total: 13.7ms	remaining: 27.4ms
10:	learn: 0.8244382	total: 14.1ms	remaining: 24.4ms
11:	learn: 0.8258427	total: 15.1ms	remaining: 22.7ms
12:	learn: 0.8286517	total: 16.1ms	remaining: 21ms
13:	learn: 0.8244382	total: 17.4ms	remaining: 19.9ms
14:	learn: 0.8314607	total: 18.4ms	remaining: 18.4ms
15:	learn: 0.8370787	total: 19.4ms	remaining: 17ms
16:	learn: 0.8370787	total: 20.8ms	remaining: 15.9ms
17:	learn: 0.8384831	total: 22.3ms	remaining: 14.9ms
18:	learn: 0.8370787	total: 22.9ms	remaining: 13.3ms
19:	learn: 0.8455056	total: 23.9ms	remaining: 11.9ms
20:	learn: 0.8441011	total: 24.9ms	remaining: 10.7ms
21:	learn: 0.8412921	total: 25.8ms	remaining: 9.38ms
22:	learn: 0.8412921	total: 26.2ms	remaining: 7.97ms
23:	learn: 0.8455056	total: 26.8ms	remaining: 6.7ms
24:	learn: 0.8497191	total: 27.8ms	remaining: 5.55ms
25:	learn: 0.8539326	total: 28.7ms	remaining: 4.42ms
26:	learn: 0.8483146	total: 29.7ms	remaining: 3.3ms
27:	learn: 0.8497191	total: 30.7ms	remaining: 2.19ms
28:	learn: 0.8455056	total: 31.6ms	remaining: 1.09ms
29:	learn: 0.8455056	total: 32.6ms	remaining: 0us
Learning rate set to 0.170551
0:	learn: 0.8075843	total: 951us	remaining: 37.1ms
1:	learn: 0.8117978	total: 2.28ms	remaining: 43.3ms
2:	learn: 0.8132022	total: 3.31ms	remaining: 40.8ms
3:	learn: 0.8089888	total: 4.63ms	remaining: 41.6ms
34:	learn: 0.8345021	total: 21.6ms	remaining: 9.24ms
35:	learn: 0.8345021	total: 22.2ms	remaining: 8.65ms
36:	learn: 0.8373072	total: 22.9ms	remaining: 8.04ms
37:	learn: 0.8359046	total: 23.5ms	remaining: 7.43ms
38:	learn: 0.8373072	total: 24.2ms	remaining: 6.83ms
39:	learn: 0.8401122	total: 24.9ms	remaining: 6.23ms
40:	learn: 0.8443198	total: 25.6ms	remaining: 5.62ms
41:	learn: 0.8443198	total: 26.3ms	remaining: 5ms
42:	learn: 0.8527349	total: 27ms	remaining: 4.39ms
43:	learn: 0.8555400	total: 27.7ms	remaining: 3.77ms
44:	learn: 0.8513324	total: 28.3ms	remaining: 3.15ms
45:	learn: 0.8499299	total: 29ms	remaining: 2.52ms
46:	learn: 0.8513324	total: 29.6ms	remaining: 1.89ms
47:	learn: 0.8513324	total: 30.2ms	remaining: 1.26ms
48:	learn: 0.8527349	total: 30.8ms	remaining: 629us
49:	learn: 0.8429173	total: 31.5ms	remaining: 0us
Learning rate set to 0.222169
0:	learn: 0.8232819	total: 3.55ms	remaining: 103ms
1:	learn: 0.8148668	total: 5.79ms	remaining: 81ms
2:	learn: 0.8162693	total: 6.72ms	remaining: 60.5ms
3:	learn: 0.8162693	total: 8.98ms	remaining: 58.4ms
4:	learn: 0.8064516	total: 9.65ms	remaining: 48.2ms
5:	learn: 0.8148668	total: 10.5ms	remaining: 42.2ms
6:	learn: 0.8162693	total: 10.9ms	remaining: 35.9ms
7:	learn: 0.8162693	total: 11.8ms	remaining: 32.4ms
8:	learn: 0.8288920	total: 12.8ms	remaining: 29.8ms
9:	learn: 0.8260870	total: 13.6ms	remaining: 27.2ms
10:	learn: 0.8274895	total: 14.5ms	remaining: 25ms
11:	learn: 0.8260870	total: 15.3ms	remaining: 23ms
12:	learn: 0.8288920	total: 16.2ms	remaining: 21.1ms
13:	learn: 0.8415147	total: 17ms	remaining: 19.4ms
14:	learn: 0.8457223	total: 17.8ms	remaining: 17.8ms
15:	learn: 0.8457223	total: 18.7ms	remaining: 16.3ms
16:	learn: 0.8471248	total: 19.5ms	remaining: 14.9ms
17:	learn: 0.8471248	total: 20.4ms	remaining: 13.6ms
18:	learn: 0.8471248	total: 20.8ms	remaining: 12.1ms
19:	learn: 0.8485273	total: 22ms	remaining: 11ms
20:	learn: 0.8471248	total: 22.9ms	remaining: 9.79ms
21:	learn: 0.8527349	total: 23.7ms	remaining: 8.62ms
22:	learn: 0.8541374	total: 24.5ms	remaining: 7.47ms
23:	learn: 0.8555400	total: 25.4ms	remaining: 6.35ms
24:	learn: 0.8555400	total: 26.2ms	remaining: 5.25ms
25:	learn: 0.8583450	total: 27ms	remaining: 4.16ms
26:	learn: 0.8555400	total: 27.9ms	remaining: 3.1ms
27:	learn: 0.8569425	total: 28.9ms	remaining: 2.06ms
28:	learn: 0.8583450	total: 29.7ms	remaining: 1.02ms
29:	learn: 0.8611501	total: 30.6ms	remaining: 0us
Learning rate set to 0.170653
0:	learn: 0.7924264	total: 1.11ms	remaining: 43.2ms
1:	learn: 0.7868163	total: 1.48ms	remaining: 28.2ms
2:	learn: 0.7868163	total: 2.28ms	remaining: 28.1ms
3:	learn: 0.7896213	total: 3.36ms	remaining: 30.2ms
4:	learn: 0.7952314	total: 3.78ms	remaining: 26.5ms
5:	learn: 0.8008415	total: 4.41ms	remaining: 25ms
6:	learn: 0.8078541	total: 5.22ms	remaining: 24.6ms
7:	learn: 0.8078541	total: 6.37ms	remaining: 25.5ms
8:	learn: 0.8134642	total: 6.85ms	remaining: 23.6ms
9:	learn: 0.8148668	total: 7.65ms	remaining: 22.9ms
10:	learn: 0.8120617	total: 8.63ms	remaining: 22.8ms
11:	learn: 0.8162693	total: 9.43ms	remaining: 22ms
12:	learn: 0.8120617	total: 9.74ms	remaining: 20.2ms
13:	learn: 0.8134642	total: 10.5ms	remaining: 19.5ms
14:	learn: 0.8134642	total: 10.9ms	remaining: 18.2ms
15:	learn: 0.8148668	total: 11.6ms	remaining: 17.4ms
16:	learn: 0.8232819	total: 12.5ms	remaining: 16.8ms
17:	learn: 0.8218794	total: 13.2ms	remaining: 16.2ms
18:	learn: 0.8302945	total: 13.6ms	remaining: 15ms
19:	learn: 0.8359046	total: 14.4ms	remaining: 14.4ms
20:	learn: 0.8387097	total: 15.1ms	remaining: 13.7ms
21:	learn: 0.8401122	total: 15.9ms	remaining: 13ms
22:	learn: 0.8359046	total: 16.6ms	remaining: 12.3ms

In [38]:
from sklearn.ensemble import RandomForestClassifier
rf = RandomForestClassifier(max_depth=2, random_state=0)

In [40]:
start = time.time_ns()
param_test = {"max_depth":[2,3,4,8]}
gs_rf = GridSearchCV(estimator = rf, param_grid = param_test, scoring='roc_auc',n_jobs=-1,cv=5)
gs_rf.fit(X,y)
end = time.time_ns()
print(gs_rf.best_params_,gs_rf.best_score_)
print(gs_rf.cv_results_['mean_test_score'])
print('**************')
print('TIME USED (ms):', (end-start)/1000)

{'max_depth': 8} 0.8691885270262872
[0.84435619 0.85402126 0.85756261 0.86918853]
**************
TIME USED (ms): 651655.501
3:	learn: 0.8078541	total: 4.88ms	remaining: 31.7ms
4:	learn: 0.8078541	total: 6.93ms	remaining: 34.6ms
5:	learn: 0.8162693	total: 7.7ms	remaining: 30.8ms
6:	learn: 0.8148668	total: 8.18ms	remaining: 26.9ms
7:	learn: 0.8232819	total: 8.86ms	remaining: 24.4ms
8:	learn: 0.8288920	total: 10.4ms	remaining: 24.2ms
9:	learn: 0.8302945	total: 11.1ms	remaining: 22.2ms
10:	learn: 0.8345021	total: 12.1ms	remaining: 20.8ms
11:	learn: 0.8302945	total: 12.7ms	remaining: 19ms
12:	learn: 0.8302945	total: 13.3ms	remaining: 17.4ms
13:	learn: 0.8345021	total: 13.9ms	remaining: 15.9ms
14:	learn: 0.8330996	total: 14.6ms	remaining: 14.6ms
15:	learn: 0.8330996	total: 15.2ms	remaining: 13.3ms
16:	learn: 0.8359046	total: 15.8ms	remaining: 12.1ms
17:	learn: 0.8373072	total: 16.4ms	remaining: 10.9ms
18:	learn: 0.8429173	total: 16.9ms	remaining: 9.76ms
19:	learn: 0.8457223	total: 17.2ms	remaining: 8.6ms
20:	learn: 0.8443198	total: 17.8ms	remaining: 7.62ms
21:	learn: 0.8457223	total: 18.4ms	remaining: 6.7ms
22:	learn: 0.8443198	total: 19.1ms	remaining: 5.8ms
23:	learn: 0.8485273	total: 19.7ms	remaining: 4.92ms
24:	learn: 0.8541374	total: 20.3ms	remaining: 4.06ms
25:	learn: 0.8555400	total: 20.9ms	remaining: 3.22ms
26:	learn: 0.8569425	total: 21.9ms	remaining: 2.43ms
27:	learn: 0.8555400	total: 22.9ms	remaining: 1.64ms
28:	learn: 0.8569425	total: 23.5ms	remaining: 811us
29:	learn: 0.8583450	total: 24.2ms	remaining: 0us
Learning rate set to 0.222169
0:	learn: 0.7882188	total: 1.06ms	remaining: 30.9ms
1:	learn: 0.7868163	total: 1.43ms	remaining: 20.1ms
2:	learn: 0.7868163	total: 1.74ms	remaining: 15.7ms
3:	learn: 0.7868163	total: 2.39ms	remaining: 15.6ms
4:	learn: 0.7994390	total: 2.92ms	remaining: 14.6ms
5:	learn: 0.8050491	total: 3.56ms	remaining: 14.3ms
6:	learn: 0.8036466	total: 3.96ms	remaining: 13ms
7:	learn: 0.8064516	total: 4.66ms	remaining: 12.8ms
8:	learn: 0.8050491	total: 5.27ms	remaining: 12.3ms
9:	learn: 0.8064516	total: 5.93ms	remaining: 11.9ms
10:	learn: 0.8064516	total: 6.36ms	remaining: 11ms
11:	learn: 0.8078541	total: 7ms	remaining: 10.5ms
12:	learn: 0.8134642	total: 7.66ms	remaining: 10ms
13:	learn: 0.8176718	total: 8.26ms	remaining: 9.44ms
14:	learn: 0.8246844	total: 8.9ms	remaining: 8.9ms
15:	learn: 0.8232819	total: 9.29ms	remaining: 8.13ms
16:	learn: 0.8260870	total: 9.93ms	remaining: 7.59ms
17:	learn: 0.8246844	total: 10.2ms	remaining: 6.78ms
18:	learn: 0.8260870	total: 10.8ms	remaining: 6.25ms
19:	learn: 0.8246844	total: 12.1ms	remaining: 6.06ms
20:	learn: 0.8260870	total: 12.8ms	remaining: 5.48ms
21:	learn: 0.8260870	total: 13.4ms	remaining: 4.88ms
22:	learn: 0.8288920	total: 14ms	remaining: 4.27ms
23:	learn: 0.8288920	total: 14.6ms	remaining: 3.66ms
24:	learn: 0.8316971	total: 15.2ms	remaining: 3.05ms
25:	learn: 0.8345021	total: 15.8ms	remaining: 2.44ms
26:	learn: 0.8345021	total: 16.5ms	remaining: 1.83ms
27:	learn: 0.8373072	total: 17.1ms	remaining: 1.22ms
28:	learn: 0.8387097	total: 17.7ms	remaining: 611us
29:	learn: 0.8415147	total: 18.3ms	remaining: 0us
Learning rate set to 0.170653
0:	learn: 0.8232819	total: 834us	remaining: 32.6ms
1:	learn: 0.7952314	total: 1.12ms	remaining: 21.3ms
2:	learn: 0.7952314	total: 1.74ms	remaining: 21.4ms
3:	learn: 0.8078541	total: 2.34ms	remaining: 21ms
4:	learn: 0.8106592	total: 3ms	remaining: 21ms
5:	learn: 0.8190743	total: 3.62ms	remaining: 20.5ms
6:	learn: 0.8190743	total: 4.19ms	remaining: 19.8ms
7:	learn: 0.8260870	total: 4.81ms	remaining: 19.2ms
8:	learn: 0.8246844	total: 5.38ms	remaining: 18.6ms
9:	learn: 0.8232819	total: 5.98ms	remaining: 17.9ms
10:	learn: 0.8316971	total: 6.58ms	remaining: 17.4ms
11:	learn: 0.8316971	total: 7.17ms	remaining: 16.7ms
12:	learn: 0.8359046	total: 7.81ms	remaining: 16.2ms
13:	learn: 0.8345021	total: 8.41ms	remaining: 15.6ms
14:	learn: 0.8373072	total: 9ms	remaining: 15ms
15:	learn: 0.8401122	total: 9.6ms	remaining: 14.4ms
16:	learn: 0.8443198	total: 10.2ms	remaining: 13.8ms
17:	learn: 0.8485273	total: 10.9ms	remaining: 13.3ms
18:	learn: 0.8471248	total: 11.5ms	remaining: 12.7ms
19:	learn: 0.8499299	total: 12.1ms	remaining: 12.1ms
20:	learn: 0.8541374	total: 12.7ms	remaining: 11.5ms
21:	learn: 0.8541374	total: 13.8ms	remaining: 11.3ms
22:	learn: 0.8555400	total: 14.4ms	remaining: 10.7ms
23:	learn: 0.8541374	total: 15ms	remaining: 10ms
24:	learn: 0.8555400	total: 15.6ms	remaining: 9.38ms
25:	learn: 0.8541374	total: 16.2ms	remaining: 8.74ms
26:	learn: 0.8541374	total: 16.8ms	remaining: 8.1ms
27:	learn: 0.8555400	total: 17.4ms	remaining: 7.47ms
28:	learn: 0.8569425	total: 18ms	remaining: 6.84ms
29:	learn: 0.8555400	total: 18.4ms	remaining: 6.14ms
30:	learn: 0.8555400	total: 19ms	remaining: 5.52ms
31:	learn: 0.8555400	total: 19.6ms	remaining: 4.91ms
32:	learn: 0.8569425	total: 20.2ms	remaining: 4.29ms
33:	learn: 0.8569425	total: 20.6ms	remaining: 3.64ms
34:	learn: 0.8583450	total: 21.1ms	remaining: 3.01ms
35:	learn: 0.8583450	total: 21.7ms	remaining: 2.41ms
36:	learn: 0.8583450	total: 22ms	remaining: 1.78ms
37:	learn: 0.8597475	total: 22.6ms	remaining: 1.19ms
38:	learn: 0.8583450	total: 23.2ms	remaining: 594us
39:	learn: 0.8597475	total: 23.8ms	remaining: 0us
Learning rate set to 0.139075
0:	learn: 0.7924264	total: 779us	remaining: 38.2ms
1:	learn: 0.7868163	total: 1.05ms	remaining: 25.3ms
2:	learn: 0.7868163	total: 2.05ms	remaining: 32.1ms
3:	learn: 0.7896213	total: 2.69ms	remaining: 31ms
4:	learn: 0.7924264	total: 3.03ms	remaining: 27.3ms
5:	learn: 0.8008415	total: 3.5ms	remaining: 25.7ms
6:	learn: 0.8120617	total: 4.12ms	remaining: 25.3ms
7:	learn: 0.8148668	total: 4.94ms	remaining: 26ms
8:	learn: 0.8162693	total: 5.54ms	remaining: 25.2ms
9:	learn: 0.8148668	total: 6.13ms	remaining: 24.5ms
10:	learn: 0.8134642	total: 6.76ms	remaining: 24ms
11:	learn: 0.8162693	total: 7.36ms	remaining: 23.3ms
12:	learn: 0.8148668	total: 8.02ms	remaining: 22.8ms
13:	learn: 0.8162693	total: 8.33ms	remaining: 21.4ms
14:	learn: 0.8162693	total: 8.94ms	remaining: 20.9ms
15:	learn: 0.8176718	total: 9.18ms	remaining: 19.5ms
16:	learn: 0.8190743	total: 9.79ms	remaining: 19ms
17:	learn: 0.8232819	total: 10.7ms	remaining: 19.1ms
18:	learn: 0.8232819	total: 11.4ms	remaining: 18.6ms
19:	learn: 0.8246844	total: 11.9ms	remaining: 17.8ms
20:	learn: 0.8260870	total: 12.5ms	remaining: 17.3ms
21:	learn: 0.8260870	total: 13.2ms	remaining: 16.7ms
22:	learn: 0.8260870	total: 13.8ms	remaining: 16.2ms
23:	learn: 0.8316971	total: 14.4ms	remaining: 15.6ms
24:	learn: 0.8330996	total: 15ms	remaining: 15ms
25:	learn: 0.8345021	total: 15.6ms	remaining: 14.4ms
26:	learn: 0.8330996	total: 16.3ms	remaining: 13.8ms
27:	learn: 0.8330996	total: 17ms	remaining: 13.3ms
28:	learn: 0.8373072	total: 17.5ms	remaining: 12.7ms
29:	learn: 0.8387097	total: 17.9ms	remaining: 12ms
30:	learn: 0.8373072	total: 18.5ms	remaining: 11.4ms
31:	learn: 0.8373072	total: 19ms	remaining: 10.7ms
32:	learn: 0.8345021	total: 19.6ms	remaining: 10.1ms
33:	learn: 0.8345021	total: 20.2ms	remaining: 9.52ms
34:	learn: 0.8330996	total: 20.8ms	remaining: 8.93ms
35:	learn: 0.8429173	total: 21.4ms	remaining: 8.33ms
36:	learn: 0.8387097	total: 22ms	remaining: 7.74ms
37:	learn: 0.8443198	total: 22.6ms	remaining: 7.14ms
38:	learn: 0.8443198	total: 22.9ms	remaining: 6.45ms
39:	learn: 0.8443198	total: 23.2ms	remaining: 5.81ms
40:	learn: 0.8429173	total: 23.6ms	remaining: 5.17ms
41:	learn: 0.8457223	total: 24.1ms	remaining: 4.6ms
42:	learn: 0.8457223	total: 24.8ms	remaining: 4.03ms
43:	learn: 0.8457223	total: 25.4ms	remaining: 3.46ms
44:	learn: 0.8471248	total: 26ms	remaining: 2.89ms
45:	learn: 0.8471248	total: 26.2ms	remaining: 2.28ms
46:	learn: 0.8499299	total: 26.9ms	remaining: 1.71ms
47:	learn: 0.8499299	total: 27.5ms	remaining: 1.14ms
48:	learn: 0.8513324	total: 28.1ms	remaining: 573us
49:	learn: 0.8499299	total: 28.7ms	remaining: 0us
28:	learn: 0.8429173	total: 20.7ms	remaining: 15ms
29:	learn: 0.8415147	total: 21.4ms	remaining: 14.3ms
30:	learn: 0.8457223	total: 22.2ms	remaining: 13.6ms
31:	learn: 0.8471248	total: 23ms	remaining: 12.9ms
32:	learn: 0.8457223	total: 23.8ms	remaining: 12.2ms
33:	learn: 0.8457223	total: 24.5ms	remaining: 11.5ms
34:	learn: 0.8485273	total: 25.3ms	remaining: 10.8ms
35:	learn: 0.8471248	total: 25.8ms	remaining: 10ms
36:	learn: 0.8499299	total: 26.6ms	remaining: 9.34ms
37:	learn: 0.8499299	total: 27.3ms	remaining: 8.64ms
38:	learn: 0.8499299	total: 28.1ms	remaining: 7.93ms
39:	learn: 0.8499299	total: 28.5ms	remaining: 7.13ms
40:	learn: 0.8499299	total: 29.3ms	remaining: 6.42ms
41:	learn: 0.8513324	total: 30ms	remaining: 5.72ms
42:	learn: 0.8499299	total: 30.8ms	remaining: 5.01ms
43:	learn: 0.8499299	total: 31.1ms	remaining: 4.24ms
44:	learn: 0.8541374	total: 31.8ms	remaining: 3.54ms
45:	learn: 0.8555400	total: 32.5ms	remaining: 2.83ms
46:	learn: 0.8555400	total: 33.3ms	remaining: 2.13ms
47:	learn: 0.8527349	total: 34.4ms	remaining: 1.43ms
48:	learn: 0.8541374	total: 35.1ms	remaining: 716us
49:	learn: 0.8569425	total: 35.9ms	remaining: 0us
28:	learn: 0.8176718	total: 24.9ms	remaining: 18ms
29:	learn: 0.8204769	total: 25.8ms	remaining: 17.2ms
30:	learn: 0.8190743	total: 26.8ms	remaining: 16.4ms
31:	learn: 0.8190743	total: 27.7ms	remaining: 15.6ms
32:	learn: 0.8218794	total: 28.6ms	remaining: 14.7ms
33:	learn: 0.8190743	total: 29.5ms	remaining: 13.9ms
34:	learn: 0.8246844	total: 30.4ms	remaining: 13ms
35:	learn: 0.8274895	total: 31.4ms	remaining: 12.2ms
36:	learn: 0.8274895	total: 32.3ms	remaining: 11.3ms
37:	learn: 0.8260870	total: 33.2ms	remaining: 10.5ms
38:	learn: 0.8274895	total: 34.1ms	remaining: 9.61ms
39:	learn: 0.8288920	total: 35ms	remaining: 8.75ms
40:	learn: 0.8288920	total: 35.5ms	remaining: 7.78ms
41:	learn: 0.8302945	total: 36.4ms	remaining: 6.93ms
42:	learn: 0.8316971	total: 37.3ms	remaining: 6.07ms
43:	learn: 0.8359046	total: 38.2ms	remaining: 5.21ms
44:	learn: 0.8330996	total: 39.2ms	remaining: 4.35ms
45:	learn: 0.8345021	total: 40.1ms	remaining: 3.48ms
46:	learn: 0.8345021	total: 40.6ms	remaining: 2.59ms
47:	learn: 0.8359046	total: 41.5ms	remaining: 1.73ms
48:	learn: 0.8415147	total: 42.4ms	remaining: 865us
49:	learn: 0.8415147	total: 42.8ms	remaining: 0us
4:	learn: 0.8089888	total: 5.4ms	remaining: 37.8ms
5:	learn: 0.8132022	total: 5.96ms	remaining: 33.8ms
6:	learn: 0.8160112	total: 6.93ms	remaining: 32.7ms
7:	learn: 0.8160112	total: 7.95ms	remaining: 31.8ms
8:	learn: 0.8146067	total: 8.96ms	remaining: 30.9ms
9:	learn: 0.8174157	total: 9.98ms	remaining: 30ms
10:	learn: 0.8216292	total: 11ms	remaining: 29ms
11:	learn: 0.8202247	total: 11.8ms	remaining: 27.5ms
12:	learn: 0.8300562	total: 12.7ms	remaining: 26.4ms
13:	learn: 0.8244382	total: 13.7ms	remaining: 25.5ms
14:	learn: 0.8272472	total: 14.7ms	remaining: 24.5ms
15:	learn: 0.8314607	total: 15.7ms	remaining: 23.6ms
16:	learn: 0.8244382	total: 16.2ms	remaining: 21.9ms
17:	learn: 0.8300562	total: 17.1ms	remaining: 20.9ms
18:	learn: 0.8328652	total: 18.1ms	remaining: 20ms
19:	learn: 0.8356742	total: 19.1ms	remaining: 19.1ms
20:	learn: 0.8356742	total: 19.5ms	remaining: 17.6ms
21:	learn: 0.8412921	total: 20.4ms	remaining: 16.7ms
22:	learn: 0.8370787	total: 21.4ms	remaining: 15.8ms
23:	learn: 0.8384831	total: 22.3ms	remaining: 14.9ms
24:	learn: 0.8370787	total: 23.1ms	remaining: 13.9ms
25:	learn: 0.8412921	total: 24ms	remaining: 12.9ms
26:	learn: 0.8412921	total: 25ms	remaining: 12ms
27:	learn: 0.8483146	total: 26ms	remaining: 11.1ms
28:	learn: 0.8469101	total: 27.1ms	remaining: 10.3ms
29:	learn: 0.8441011	total: 28.2ms	remaining: 9.4ms
30:	learn: 0.8441011	total: 28.6ms	remaining: 8.31ms
31:	learn: 0.8469101	total: 30ms	remaining: 7.49ms
32:	learn: 0.8455056	total: 49.5ms	remaining: 10.5ms
33:	learn: 0.8469101	total: 50.6ms	remaining: 8.93ms
34:	learn: 0.8469101	total: 51.6ms	remaining: 7.37ms
35:	learn: 0.8455056	total: 52.6ms	remaining: 5.84ms
36:	learn: 0.8469101	total: 53.5ms	remaining: 4.34ms
37:	learn: 0.8483146	total: 54.5ms	remaining: 2.87ms
38:	learn: 0.8441011	total: 55.4ms	remaining: 1.42ms
39:	learn: 0.8469101	total: 56.3ms	remaining: 0us
Learning rate set to 0.139075
0:	learn: 0.8050491	total: 1.09ms	remaining: 53.6ms
1:	learn: 0.8036466	total: 1.7ms	remaining: 40.7ms
2:	learn: 0.8036466	total: 2.19ms	remaining: 34.3ms
3:	learn: 0.8036466	total: 3.22ms	remaining: 37ms
4:	learn: 0.8148668	total: 4.81ms	remaining: 43.3ms
5:	learn: 0.8148668	total: 5.83ms	remaining: 42.7ms
6:	learn: 0.8204769	total: 6.86ms	remaining: 42.2ms
7:	learn: 0.8176718	total: 7.48ms	remaining: 39.3ms
8:	learn: 0.8204769	total: 8.45ms	remaining: 38.5ms
9:	learn: 0.8218794	total: 9.43ms	remaining: 37.7ms
10:	learn: 0.8218794	total: 10.4ms	remaining: 36.9ms
11:	learn: 0.8246844	total: 11.4ms	remaining: 36ms
12:	learn: 0.8246844	total: 12ms	remaining: 34.2ms
13:	learn: 0.8246844	total: 12.9ms	remaining: 33.3ms
14:	learn: 0.8260870	total: 18.6ms	remaining: 43.4ms
15:	learn: 0.8359046	total: 19.6ms	remaining: 41.7ms
16:	learn: 0.8373072	total: 20.6ms	remaining: 40ms
17:	learn: 0.8373072	total: 21.1ms	remaining: 37.6ms
18:	learn: 0.8387097	total: 22.1ms	remaining: 36ms
19:	learn: 0.8415147	total: 23ms	remaining: 34.5ms
20:	learn: 0.8415147	total: 24ms	remaining: 33.1ms
21:	learn: 0.8485273	total: 24.8ms	remaining: 31.5ms
22:	learn: 0.8457223	total: 25.8ms	remaining: 30.2ms
23:	learn: 0.8527349	total: 26.1ms	remaining: 28.3ms
24:	learn: 0.8555400	total: 27.1ms	remaining: 27.1ms
25:	learn: 0.8513324	total: 28.1ms	remaining: 25.9ms
26:	learn: 0.8499299	total: 29.1ms	remaining: 24.8ms
27:	learn: 0.8611501	total: 30.1ms	remaining: 23.6ms
28:	learn: 0.8625526	total: 31.1ms	remaining: 22.5ms
29:	learn: 0.8611501	total: 32ms	remaining: 21.4ms
30:	learn: 0.8611501	total: 33ms	remaining: 20.2ms
31:	learn: 0.8611501	total: 34ms	remaining: 19.1ms
32:	learn: 0.8611501	total: 35ms	remaining: 18ms
33:	learn: 0.8625526	total: 35.7ms	remaining: 16.8ms
34:	learn: 0.8653576	total: 36.6ms	remaining: 15.7ms
35:	learn: 0.8667602	total: 37.6ms	remaining: 14.6ms
36:	learn: 0.8667602	total: 38.5ms	remaining: 13.5ms
37:	learn: 0.8667602	total: 39.5ms	remaining: 12.5ms
38:	learn: 0.8681627	total: 40.6ms	remaining: 11.5ms
39:	learn: 0.8709677	total: 41.7ms	remaining: 10.4ms
40:	learn: 0.8681627	total: 42.6ms	remaining: 9.35ms
41:	learn: 0.8709677	total: 43.6ms	remaining: 8.3ms
42:	learn: 0.8667602	total: 44.5ms	remaining: 7.25ms
43:	learn: 0.8695652	total: 45.5ms	remaining: 6.21ms
44:	learn: 0.8681627	total: 45.9ms	remaining: 5.1ms
45:	learn: 0.8695652	total: 46.9ms	remaining: 4.08ms
46:	learn: 0.8695652	total: 47.9ms	remaining: 3.06ms
47:	learn: 0.8751753	total: 48.9ms	remaining: 2.04ms
48:	learn: 0.8751753	total: 49.6ms	remaining: 1.01ms
49:	learn: 0.8723703	total: 50.5ms	remaining: 0us