In [1]:
import pandas as pd
import seaborn as sns
import numpy as np

In [2]:
data = pd.read_csv('/Users/nkerstingadxnet.com/Documents/Higgs/orig/atlas-higgs-challenge-2014-v2.csv')

In [3]:
data.head()

,EventId,DER_mass_MMC,DER_mass_transverse_met_lep,DER_mass_vis,DER_pt_h,DER_deltaeta_jet_jet,DER_mass_jet_jet,DER_prodeta_jet_jet,DER_deltar_tau_lep,DER_pt_tot,...,PRI_jet_leading_eta,PRI_jet_leading_phi,PRI_jet_subleading_pt,PRI_jet_subleading_eta,PRI_jet_subleading_phi,PRI_jet_all_pt,Weight,Label,KaggleSet,KaggleWeight
0,100000,138.470,51.655,97.827,27.980,0.91,124.711,2.666,3.064,41.928,...,2.150,0.444,46.062,1.24,-2.475,113.497,0.000814,s,t,0.002653
1,100001,160.937,68.768,103.235,48.146,-999.00,-999.000,-999.000,3.473,2.078,...,0.725,1.158,-999.000,-999.00,-999.000,46.226,0.681042,b,t,2.233584
2,100002,-999.000,162.172,125.953,35.635,-999.00,-999.000,-999.000,3.148,9.336,...,2.053,-2.028,-999.000,-999.00,-999.000,44.251,0.715742,b,t,2.347389
3,100003,143.905,81.417,80.943,0.414,-999.00,-999.000,-999.000,3.310,0.414,...,-999.000,-999.000,-999.000,-999.00,-999.000,-0.000,1.660654,b,t,5.446378
4,100004,175.864,16.915,134.805,16.405,-999.00,-999.000,-999.000,3.891,16.405,...,-999.000,-999.000,-999.000,-999.00,-999.000,0.000,1.904263,b,t,6.245333

In [5]:
data.describe()

,EventId,DER_mass_MMC,DER_mass_transverse_met_lep,DER_mass_vis,DER_pt_h,DER_deltaeta_jet_jet,DER_mass_jet_jet,DER_prodeta_jet_jet,DER_deltar_tau_lep,DER_pt_tot,...,PRI_jet_num,PRI_jet_leading_pt,PRI_jet_leading_eta,PRI_jet_leading_phi,PRI_jet_subleading_pt,PRI_jet_subleading_eta,PRI_jet_subleading_phi,PRI_jet_all_pt,Weight,KaggleWeight
count,818238.000000,818238.000000,818238.000000,818238.000000,818238.000000,818238.000000,818238.000000,818238.000000,818238.000000,818238.000000,...,818238.000000,818238.000000,818238.000000,818238.000000,818238.000000,818238.000000,818238.000000,818238.000000,818238.000000,818238.000000
mean,509118.500000,-48.819019,49.252714,81.140561,57.849524,-707.740880,-600.191191,-708.681306,2.373871,18.969617,...,0.979923,-348.757840,-399.693294,-399.703858,-691.626111,-708.442206,-708.443312,73.205594,0.503144,2.012577
std,236205.109119,406.118397,35.378609,40.582708,63.411938,454.793899,658.724040,453.328599,0.780875,21.918491,...,0.978793,533.097006,489.428560,489.420013,480.274744,453.699150,453.697158,98.331754,0.572200,5.439641
min,100000.000000,-999.000000,0.000000,6.329000,0.000000,-999.000000,-999.000000,-999.000000,0.208000,0.000000,...,0.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-0.000000,0.000461,0.000839
25%,304559.250000,78.166000,19.304000,59.414000,14.164250,-999.000000,-999.000000,-999.000000,1.814000,2.839000,...,0.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,-999.000000,0.000000,0.005721,0.010415
50%,509118.500000,105.061000,46.484000,73.744000,38.470000,-999.000000,-999.000000,-999.000000,2.492000,12.383000,...,1.000000,38.965000,-1.865000,-2.105000,-999.000000,-999.000000,-999.000000,40.506000,0.357223,0.806562
75%,713677.750000,130.730000,73.620000,92.188000,79.226750,0.499000,84.031750,-4.548000,2.962000,27.634000,...,2.000000,75.470750,0.432000,0.489000,33.800000,-2.436000,-2.265000,110.387000,0.733462,2.360271
max,918237.000000,1949.261000,968.669000,1349.351000,2834.999000,8.724000,4974.979000,17.650000,5.751000,2834.999000,...,3.000000,1163.439000,4.500000,3.142000,817.801000,4.500000,3.142000,1860.175000,2.386316,106.908407

In [6]:
# now replace all the '-999' values with NULL so we can properly handle them
nulled_data = data.replace(-999.0, np.nan)
nulled_data.info()
nulled_data.isnull().sum()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 818238 entries, 0 to 818237
Data columns (total 35 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   EventId                      818238 non-null  int64
 1   DER_mass_MMC                 693636 non-null  float64
 2   DER_mass_transverse_met_lep  818238 non-null  float64
 3   DER_mass_vis                 818238 non-null  float64
 4   DER_pt_h                     818238 non-null  float64
 5   DER_deltaeta_jet_jet         237985 non-null  float64
 6   DER_mass_jet_jet             237985 non-null  float64
 7   DER_prodeta_jet_jet          237985 non-null  float64
 8   DER_deltar_tau_lep           818238 non-null  float64
 9   DER_pt_tot                   818238 non-null  float64
 10  DER_sum_pt                   818238 non-null  float64
 11  DER_pt_ratio_lep_tau         818238 non-null  float64
 12  DER_met_phi_centrality       818238 non-null  float64
 13  DER_lep_eta_centrality       237985 non-null  float64
 14  PRI_tau_pt                   818238 non-null  float64
 15  PRI_tau_eta                  818238 non-null  float64
 16  PRI_tau_phi                  818238 non-null  float64
 17  PRI_lep_pt                   818238 non-null  float64
 18  PRI_lep_eta                  818238 non-null  float64
 19  PRI_lep_phi                  818238 non-null  float64
 20  PRI_met                      818238 non-null  float64
 21  PRI_met_phi                  818238 non-null  float64
 22  PRI_met_sumet                818238 non-null  float64
 23  PRI_jet_num                  818238 non-null  int64
 24  PRI_jet_leading_pt           490867 non-null  float64
 25  PRI_jet_leading_eta          490867 non-null  float64
 26  PRI_jet_leading_phi          490867 non-null  float64
 27  PRI_jet_subleading_pt        237985 non-null  float64
 28  PRI_jet_subleading_eta       237985 non-null  float64
 29  PRI_jet_subleading_phi       237985 non-null  float64
 30  PRI_jet_all_pt               818238 non-null  float64
 31  Weight                       818238 non-null  float64
 32  Label                        818238 non-null  object
 33  KaggleSet                    818238 non-null  object
 34  KaggleWeight                 818238 non-null  float64
dtypes: float64(31), int64(2), object(2)
memory usage: 218.5+ MB

EventId                             0
DER_mass_MMC                   124602
DER_mass_transverse_met_lep         0
DER_mass_vis                        0
DER_pt_h                            0
DER_deltaeta_jet_jet           580253
DER_mass_jet_jet               580253
DER_prodeta_jet_jet            580253
DER_deltar_tau_lep                  0
DER_pt_tot                          0
DER_sum_pt                          0
DER_pt_ratio_lep_tau                0
DER_met_phi_centrality              0
DER_lep_eta_centrality         580253
PRI_tau_pt                          0
PRI_tau_eta                         0
PRI_tau_phi                         0
PRI_lep_pt                          0
PRI_lep_eta                         0
PRI_lep_phi                         0
PRI_met                             0
PRI_met_phi                         0
PRI_met_sumet                       0
PRI_jet_num                         0
PRI_jet_leading_pt             327371
PRI_jet_leading_eta            327371
PRI_jet_leading_phi            327371
PRI_jet_subleading_pt          580253
PRI_jet_subleading_eta         580253
PRI_jet_subleading_phi         580253
PRI_jet_all_pt                      0
Weight                              0
Label                               0
KaggleSet                           0
KaggleWeight                        0
dtype: int64

In [7]:
train_data = nulled_data.loc[nulled_data['KaggleSet'] == 't'].copy(deep=True)
public_test_data = nulled_data.loc[nulled_data['KaggleSet'] == 'b'].copy(deep=True)
private_test_data = nulled_data.loc[nulled_data['KaggleSet'] == 'v'].copy(deep=True)
unused_data = nulled_data.loc[data['KaggleSet'] == 'u'].copy(deep=True)

In [8]:
orig_train_data = train_data.copy()
orig_public_test_data = public_test_data.copy()
orig_private_test_data = private_test_data.copy()


# now replace the null values with column averages
train_data.drop('EventId', axis=1, inplace=True)
train_data.drop('Label', axis=1, inplace=True)
train_data.drop('Weight', axis=1, inplace=True)
train_data.drop('KaggleWeight', axis=1, inplace=True)
train_data.drop('KaggleSet', axis=1, inplace=True)
for col in train_data:
    train_data[col].fillna(train_data[col].mean(), inplace=True)
train_data.isnull().sum()


public_test_data.drop('EventId', axis=1, inplace=True)
public_test_data.drop('Label', axis=1, inplace=True)
public_test_data.drop('Weight', axis=1, inplace=True)
public_test_data.drop('KaggleWeight', axis=1, inplace=True)
public_test_data.drop('KaggleSet', axis=1, inplace=True)
for col in public_test_data:
    public_test_data[col].fillna(public_test_data[col].mean(), inplace=True)
public_test_data.isnull().sum()


private_test_data.drop('EventId', axis=1, inplace=True)
private_test_data.drop('Label', axis=1, inplace=True)
private_test_data.drop('Weight', axis=1, inplace=True)
private_test_data.drop('KaggleWeight', axis=1, inplace=True)
private_test_data.drop('KaggleSet', axis=1, inplace=True)
for col in private_test_data:
    private_test_data[col].fillna(private_test_data[col].mean(), inplace=True)
private_test_data.isnull().sum()

DER_mass_MMC                   0
DER_mass_transverse_met_lep    0
DER_mass_vis                   0
DER_pt_h                       0
DER_deltaeta_jet_jet           0
DER_mass_jet_jet               0
DER_prodeta_jet_jet            0
DER_deltar_tau_lep             0
DER_pt_tot                     0
DER_sum_pt                     0
DER_pt_ratio_lep_tau           0
DER_met_phi_centrality         0
DER_lep_eta_centrality         0
PRI_tau_pt                     0
PRI_tau_eta                    0
PRI_tau_phi                    0
PRI_lep_pt                     0
PRI_lep_eta                    0
PRI_lep_phi                    0
PRI_met                        0
PRI_met_phi                    0
PRI_met_sumet                  0
PRI_jet_num                    0
PRI_jet_leading_pt             0
PRI_jet_leading_eta            0
PRI_jet_leading_phi            0
PRI_jet_subleading_pt          0
PRI_jet_subleading_eta         0
PRI_jet_subleading_phi         0
PRI_jet_all_pt                 0
dtype: int64

In [9]:
#train_data.head()
orig_train_data.describe()
total_sig_w = orig_train_data.loc[orig_train_data['Label'] == 's', 'KaggleWeight'].sum()
total_sig = len(orig_train_data[orig_train_data['Label'] == 's'])
total_bak_w = orig_train_data.loc[orig_train_data['Label'] == 'b', 'KaggleWeight'].sum()
total_bak = len(orig_train_data[orig_train_data['Label'] == 'b'])
print(f"#S (W), #B(W), S/B(W) = {total_sig}({total_sig_w:.3f}), {total_bak}({total_bak_w:.3f}), {total_sig_w/total_bak_w:.3f}({total_sig/total_bak:.3f})")

#S (W), #B(W), S/B(W) = 85667(691.989), 164333(410999.847), 0.002(0.521)

In [10]:
orig_public_test_data.describe()
total_sig_w = orig_public_test_data.loc[orig_public_test_data['Label'] == 's', 'KaggleWeight'].sum()
total_sig = len(orig_public_test_data[orig_public_test_data['Label'] == 's'])
total_bak_w = orig_public_test_data.loc[orig_public_test_data['Label'] == 'b', 'KaggleWeight'].sum()
total_bak = len(orig_public_test_data[orig_public_test_data['Label'] == 'b'])
print(f"#S (W), #B(W), S/B(W) = {total_sig}({total_sig_w:.3f}), {total_bak}({total_bak_w:.3f}), {total_sig_w/total_bak_w:.3f}({total_sig/total_bak:.3f})")

#S (W), #B(W), S/B(W) = 34025(691.989), 65975(410999.847), 0.002(0.516)

In [11]:
orig_private_test_data.describe()
total_sig_w = orig_private_test_data.loc[orig_private_test_data['Label'] == 's', 'KaggleWeight'].sum()
total_sig = len(orig_private_test_data[orig_private_test_data['Label'] == 's'])
total_bak_w = orig_private_test_data.loc[orig_private_test_data['Label'] == 'b', 'KaggleWeight'].sum()
total_bak = len(orig_private_test_data[orig_private_test_data['Label'] == 'b'])
print(f"#S (W), #B(W), S/B(W) = {total_sig}({total_sig_w:.3f}), {total_bak}({total_bak_w:.3f}), {total_sig_w/total_bak_w:.3f}({total_sig/total_bak:.3f})")

#S (W), #B(W), S/B(W) = 153683(691.989), 296317(410999.847), 0.002(0.519)

In [12]:
# now let's normalize
normed_train_data = (train_data - train_data.min())/(train_data.max() - train_data.min())

normed_public_test_data = (public_test_data - public_test_data.min())/(public_test_data.max() - public_test_data.min())

normed_private_test_data = (private_test_data - private_test_data.min())/(private_test_data.max() - private_test_data.min())

In [13]:
normed_train_data.head()

,DER_mass_MMC,DER_mass_transverse_met_lep,DER_mass_vis,DER_pt_h,DER_deltaeta_jet_jet,DER_mass_jet_jet,DER_prodeta_jet_jet,DER_deltar_tau_lep,DER_pt_tot,DER_sum_pt,...,PRI_met_phi,PRI_met_sumet,PRI_jet_num,PRI_jet_leading_pt,PRI_jet_leading_eta,PRI_jet_leading_phi,PRI_jet_subleading_pt,PRI_jet_subleading_eta,PRI_jet_subleading_phi,PRI_jet_all_pt
0,0.109407,0.074854,0.068128,0.009869,0.107021,0.022395,0.596501,0.521549,0.014789,0.083957,...,0.455920,0.123125,0.666667,0.034326,0.738942,0.570746,0.023229,0.637778,0.106143,0.069484
1,0.128398,0.099653,0.072155,0.016983,0.282693,0.072194,0.496154,0.596238,0.000733,0.043764,...,0.195099,0.075802,0.333333,0.014878,0.580573,0.684386,0.040031,0.498684,0.499748,0.028300
2,0.095365,0.235006,0.089071,0.012570,0.282693,0.072194,0.496154,0.536888,0.003293,0.083987,...,0.152132,0.123969,0.333333,0.013067,0.728162,0.177304,0.040031,0.498684,0.499748,0.027091
3,0.114001,0.117983,0.055557,0.000146,0.282693,0.072194,0.496154,0.566472,0.000146,0.016533,...,0.509548,0.036368,0.000000,0.050269,0.499636,0.498107,0.040031,0.498684,0.499748,-0.000000
4,0.141017,0.024512,0.095662,0.005787,0.282693,0.072194,0.496154,0.672571,0.005787,0.006576,...,0.361394,0.019823,0.000000,0.050269,0.499636,0.498107,0.040031,0.498684,0.499748,0.000000

In [15]:
normed_train_data.describe()

,DER_mass_MMC,DER_mass_transverse_met_lep,DER_mass_vis,DER_pt_h,DER_deltaeta_jet_jet,DER_mass_jet_jet,DER_prodeta_jet_jet,DER_deltar_tau_lep,DER_pt_tot,DER_sum_pt,...,PRI_met_phi,PRI_met_sumet,PRI_jet_num,PRI_jet_leading_pt,PRI_jet_leading_eta,PRI_jet_leading_phi,PRI_jet_subleading_pt,PRI_jet_subleading_eta,PRI_jet_subleading_phi,PRI_jet_all_pt
count,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,...,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000,250000.000000
mean,0.095365,0.071354,0.055735,0.020422,0.282693,0.072194,0.496154,0.395380,0.006673,0.062185,...,0.498390,0.098538,0.326392,0.050269,0.499636,0.498107,0.040031,0.498684,0.499748,0.044731
std,0.044591,0.051219,0.030401,0.022454,0.110372,0.043180,0.055553,0.142971,0.007857,0.064055,...,0.288387,0.063558,0.325809,0.043099,0.153668,0.223627,0.024918,0.121605,0.155752,0.060006
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.073223,0.027882,0.039508,0.004963,0.282693,0.072194,0.496154,0.292549,0.001002,0.017409,...,0.249363,0.054936,0.000000,0.025160,0.451878,0.411587,0.040031,0.498684,0.499748,0.000000
50%,0.093758,0.067419,0.050202,0.013569,0.282693,0.072194,0.496154,0.417001,0.004344,0.041277,...,0.496181,0.083435,0.333333,0.050269,0.499636,0.498107,0.040031,0.498684,0.499748,0.024802
75%,0.102759,0.106652,0.063983,0.027926,0.282693,0.072194,0.496154,0.502739,0.009732,0.085462,...,0.748409,0.125459,0.666667,0.050269,0.548122,0.580137,0.040031,0.498684,0.499748,0.067302
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [16]:
normed_public_test_data.describe()

,DER_mass_MMC,DER_mass_transverse_met_lep,DER_mass_vis,DER_pt_h,DER_deltaeta_jet_jet,DER_mass_jet_jet,DER_prodeta_jet_jet,DER_deltar_tau_lep,DER_pt_tot,DER_sum_pt,...,PRI_met_phi,PRI_met_sumet,PRI_jet_num,PRI_jet_leading_pt,PRI_jet_leading_eta,PRI_jet_leading_phi,PRI_jet_subleading_pt,PRI_jet_subleading_eta,PRI_jet_subleading_phi,PRI_jet_all_pt
count,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,...,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000,100000.000000
mean,0.101990,0.054258,0.073720,0.043025,0.286389,0.091591,0.482320,0.390984,0.024809,0.068318,...,0.499057,0.115441,0.325543,0.048355,0.499487,0.494119,0.048145,0.499026,0.500211,0.049852
std,0.047876,0.038933,0.040431,0.047449,0.111774,0.055468,0.055253,0.143335,0.028588,0.070506,...,0.288576,0.077015,0.325739,0.041449,0.152737,0.223072,0.029968,0.122344,0.156386,0.066872
min,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,...,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000,0.000000
25%,0.077855,0.021291,0.052032,0.010082,0.286389,0.091591,0.482320,0.288370,0.003712,0.019013,...,0.248926,0.062542,0.000000,0.024457,0.451857,0.409930,0.048145,0.499026,0.500211,0.000000
50%,0.100416,0.051291,0.066254,0.028597,0.286389,0.091591,0.482320,0.412587,0.015678,0.045404,...,0.498647,0.097370,0.333333,0.048355,0.499487,0.494119,0.048145,0.499026,0.500211,0.027741
75%,0.110275,0.081076,0.084789,0.058909,0.286389,0.091591,0.482320,0.498712,0.036215,0.093973,...,0.749204,0.148355,0.666667,0.048355,0.546475,0.571292,0.048145,0.499026,0.500211,0.075256
max,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,...,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000,1.000000

In [17]:
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.model_selection import GridSearchCV

In [19]:
gb = GradientBoostingClassifier()
"""
param = {
    'n_estimators':[20,50,100,200,400],
    'max_depth': [5, 10, 15, 20],
    'learning_rate':[0.01, 0.1, 0.5]
}
"""
param = {
    'n_estimators':[10, 20, 50],
    'max_depth': [5, 10],
    'learning_rate':[0.1, 0.5]
}

clf = GridSearchCV(gb, param, cv=4, n_jobs = -1)
cv_fit = clf.fit(normed_train_data, train_labels)
x = pd.DataFrame(cv_fit.cv_results_).sort_values('mean_test_score', ascending="False")

In [20]:
x

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_learning_rate,param_max_depth,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,mean_test_score,std_test_score,rank_test_score
0,26.618923,0.330997,0.199545,0.004978,0.1,5,10,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.814176,0.816160,0.813440,0.818368,0.815536,0.001914,12
11,2193.204723,0.634014,0.213214,0.009607,0.5,10,50,"{'learning_rate': 0.5, 'max_depth': 10, 'n_est...",0.820736,0.823936,0.821760,0.824656,0.822772,0.001587,11
1,53.501251,0.191329,0.237003,0.013257,0.1,5,20,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.821648,0.823120,0.821680,0.825616,0.823016,0.001615,10
10,115.669062,0.343606,0.246330,0.020565,0.5,10,20,"{'learning_rate': 0.5, 'max_depth': 10, 'n_est...",0.828480,0.828224,0.829104,0.828576,0.828596,0.000320,9
9,58.341230,0.196490,0.235797,0.008155,0.5,10,10,"{'learning_rate': 0.5, 'max_depth': 10, 'n_est...",0.828880,0.828080,0.829136,0.830128,0.829056,0.000731,8
3,57.241883,0.404893,0.238372,0.013066,0.1,10,10,"{'learning_rate': 0.1, 'max_depth': 10, 'n_est...",0.828032,0.828816,0.828608,0.830960,0.829104,0.001109,7
6,28.224138,0.133809,0.212936,0.012993,0.5,5,10,"{'learning_rate': 0.5, 'max_depth': 5, 'n_esti...",0.828576,0.829888,0.829744,0.834112,0.830580,0.002102,6
2,139.597536,1.881623,0.286125,0.002582,0.1,5,50,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.833088,0.833968,0.832848,0.835488,0.833848,0.001035,5
7,55.963404,0.186664,0.238270,0.019773,0.5,5,20,"{'learning_rate': 0.5, 'max_depth': 5, 'n_esti...",0.834752,0.834528,0.833168,0.836160,0.834652,0.001061,4
4,115.254740,0.394828,0.281533,0.005371,0.1,10,20,"{'learning_rate': 0.1, 'max_depth': 10, 'n_est...",0.835440,0.836480,0.834848,0.836080,0.835712,0.000622,3
8,138.901786,0.565017,0.274942,0.010104,0.5,5,50,"{'learning_rate': 0.5, 'max_depth': 5, 'n_esti...",0.835408,0.836928,0.835872,0.837936,0.836536,0.000978,2
5,292.117049,3.985572,0.395020,0.002936,0.1,10,50,"{'learning_rate': 0.1, 'max_depth': 10, 'n_est...",0.839792,0.839952,0.839408,0.839920,0.839768,0.000216,1

In [23]:
gb_trial = GradientBoostingClassifier(n_estimators=50, max_depth=10, learning_rate=0.1)
gb_trial.fit(normed_train_data, train_labels)

GradientBoostingClassifier(max_depth=10, n_estimators=50)

In [24]:
import math
def AMS(s, b):
    """ Approximate Median Significance defined as:
        AMS = sqrt(
                2 { (s + b + b_r) log[1 + (s/(b+b_r))] - s}
              )        
    where b_r = 10, b = background, s = signal, log is natural logarithm """
    
    br = 10.0
    radicand = 2 *( (s+b+br) * math.log (1.0 + s/(b+br)) -s)
    if radicand < 0:
        print('radicand is negative. Exiting')
        exit()
    else:
        return math.sqrt(radicand)

In [25]:
# Training performance
y_pred = gb_trial.predict(normed_train_data)
y_gold = orig_train_data['Label']
y_weight = orig_train_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y == 's':
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TRAINING: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TRAINING: (S,B) = (517.133,21052.117), AMS=3.549, Unweighted Precision = 0.849

In [219]:
y_pred = gb_trial.predict(normed_public_test_data)
y_gold = orig_public_test_data['Label']
y_weight = orig_public_test_data['KaggleWeight']

s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y == 's':
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"VALIDATION: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

VALIDATION: (S,B) = (342.154,29665.038), AMS=1.982, Unweighted Precision = 0.698

In [220]:
y_pred = gb_trial.predict(normed_private_test_data)
y_gold = orig_private_test_data['Label']
y_weight = orig_private_test_data['KaggleWeight']

s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y == 's':
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TESTING: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TESTING: (S,B) = (320.708,37548.531), AMS=1.652, Unweighted Precision = 0.649

In [230]:
# Perhaps we are overfitting; Now try RandomForest
from sklearn.ensemble import RandomForestClassifier
rf1 = RandomForestClassifier(n_estimators=200, max_depth=13)
rf1.fit(normed_train_data, train_labels)

RandomForestClassifier(max_depth=13, n_estimators=200)

In [228]:
rf = RandomForestClassifier()

param = {
    'n_estimators':[100, 200],
    'max_depth': [10, 13]
}

clf = GridSearchCV(rf, param, cv=5, n_jobs = -1)
cv_fit = clf.fit(normed_train_data, train_labels)
x = pd.DataFrame(cv_fit.cv_results_).sort_values('mean_test_score', ascending="False")

In [229]:
x

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_max_depth,param_n_estimators,params,split0_test_score,split1_test_score,split2_test_score,split3_test_score,split4_test_score,mean_test_score,std_test_score,rank_test_score
0,75.926518,0.324974,0.838944,0.009674,10,100,"{'max_depth': 10, 'n_estimators': 100}",0.82728,0.82994,0.83044,0.82920,0.83160,0.829692,0.001437,4
1,153.081177,0.794653,1.564917,0.012721,10,200,"{'max_depth': 10, 'n_estimators': 200}",0.82822,0.82904,0.83050,0.82908,0.83202,0.829772,0.001342,3
2,94.987839,0.481594,1.024081,0.049868,13,100,"{'max_depth': 13, 'n_estimators': 100}",0.83260,0.83462,0.83532,0.83462,0.83618,0.834668,0.001183,2
3,163.682223,11.652499,1.422335,0.160423,13,200,"{'max_depth': 13, 'n_estimators': 200}",0.83296,0.83508,0.83592,0.83496,0.83668,0.835120,0.001246,1

In [231]:
# Training performance
y_pred = rf1.predict(normed_train_data)
y_gold = orig_train_data['Label']
y_weight = orig_train_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y == 's':
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TRAINING: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TRAINING: (S,B) = (490.074,21391.113), AMS=3.337, Unweighted Precision = 0.832

In [232]:
y_pred = rf1.predict(normed_public_test_data)
y_gold = orig_public_test_data['Label']
y_weight = orig_public_test_data['KaggleWeight']

s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y == 's':
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"VALIDATION: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

VALIDATION: (S,B) = (397.345,35043.806), AMS=2.118, Unweighted Precision = 0.688

In [233]:
y_pred = rf1.predict(normed_private_test_data)
y_gold = orig_private_test_data['Label']
y_weight = orig_private_test_data['KaggleWeight']

s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y == 's':
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"VALIDATION: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

VALIDATION: (S,B) = (204.602,9820.129), AMS=2.057, Unweighted Precision = 0.808

In [234]:
# now we remove all *phi features
nonphi_columns = [c for c in normed_train_data.columns if "phi" not in c]
normed_train_data_nophi = normed_train_data[nonphi_columns]
normed_public_test_data_nophi = normed_public_test_data[nonphi_columns]
normed_private_test_data_nophi = normed_private_test_data[nonphi_columns]
normed_train_data_nophi.info()

<class 'pandas.core.frame.DataFrame'>
Int64Index: 250000 entries, 0 to 249999
Data columns (total 24 columns):
 #   Column                       Non-Null Count   Dtype
---  ------                       --------------   -----
 0   DER_mass_MMC                 250000 non-null  float64
 1   DER_mass_transverse_met_lep  250000 non-null  float64
 2   DER_mass_vis                 250000 non-null  float64
 3   DER_pt_h                     250000 non-null  float64
 4   DER_deltaeta_jet_jet         250000 non-null  float64
 5   DER_mass_jet_jet             250000 non-null  float64
 6   DER_prodeta_jet_jet          250000 non-null  float64
 7   DER_deltar_tau_lep           250000 non-null  float64
 8   DER_pt_tot                   250000 non-null  float64
 9   DER_sum_pt                   250000 non-null  float64
 10  DER_pt_ratio_lep_tau         250000 non-null  float64
 11  DER_lep_eta_centrality       250000 non-null  float64
 12  PRI_tau_pt                   250000 non-null  float64
 13  PRI_tau_eta                  250000 non-null  float64
 14  PRI_lep_pt                   250000 non-null  float64
 15  PRI_lep_eta                  250000 non-null  float64
 16  PRI_met                      250000 non-null  float64
 17  PRI_met_sumet                250000 non-null  float64
 18  PRI_jet_num                  250000 non-null  float64
 19  PRI_jet_leading_pt           250000 non-null  float64
 20  PRI_jet_leading_eta          250000 non-null  float64
 21  PRI_jet_subleading_pt        250000 non-null  float64
 22  PRI_jet_subleading_eta       250000 non-null  float64
 23  PRI_jet_all_pt               250000 non-null  float64
dtypes: float64(24)
memory usage: 47.7 MB

In [161]:
gb_trial = GradientBoostingClassifier(n_estimators=100, max_depth=10, learning_rate=0.1)
gb_trial.fit(normed_train_data_nophi, train_labels)

GradientBoostingClassifier(max_depth=10)

In [235]:
rf2 = RandomForestClassifier(n_estimators=200, max_depth=13)
rf2.fit(normed_train_data_nophi, train_labels)

RandomForestClassifier(max_depth=13, n_estimators=200)

In [236]:
# Training performance
y_pred = rf2.predict(normed_train_data_nophi)
y_gold = orig_train_data['Label']
y_weight = orig_train_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y == 's':
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TRAINING: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TRAINING: (S,B) = (484.164,22178.512), AMS=3.239, Unweighted Precision = 0.826

In [237]:
y_pred = rf2.predict(normed_public_test_data_nophi)
y_gold = orig_public_test_data['Label']
y_weight = orig_public_test_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y == 's':
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TRAINING: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TRAINING: (S,B) = (388.988,38378.996), AMS=1.982, Unweighted Precision = 0.667

In [238]:
y_pred = rf2.predict(normed_private_test_data_nophi)
y_gold = orig_private_test_data['Label']
y_weight = orig_private_test_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y == 's':
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TRAINING: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TRAINING: (S,B) = (154.060,6255.661), AMS=1.938, Unweighted Precision = 0.835

In [159]:
gb = GradientBoostingClassifier()
"""
param = {
    'n_estimators':[20,50,100,200,400],
    'max_depth': [5, 10, 15, 20],
    'learning_rate':[0.01, 0.1, 0.5]
}
"""
param = {
    'n_estimators':[50, 75, 100],
    'max_depth': [5, 10, 15],
    'learning_rate':[0.1]
}

clf = GridSearchCV(gb, param, cv=2, n_jobs = -1)
cv_fit = clf.fit(normed_train_data_nophi, train_labels)
x = pd.DataFrame(cv_fit.cv_results_).sort_values('mean_test_score', ascending="False")

In [160]:
x

,mean_fit_time,std_fit_time,mean_score_time,std_score_time,param_learning_rate,param_max_depth,param_n_estimators,params,split0_test_score,split1_test_score,mean_test_score,std_test_score,rank_test_score
0,67.839825,0.023235,0.609291,0.001406,0.1,5,50,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.830832,0.831528,0.831180,0.000348,9
6,240.190936,0.250275,1.146189,0.028075,0.1,15,50,"{'learning_rate': 0.1, 'max_depth': 15, 'n_est...",0.832576,0.834232,0.833404,0.000828,8
1,103.161082,0.034942,0.694976,0.001733,0.1,5,75,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.834088,0.834944,0.834516,0.000428,7
7,333.038677,0.227583,1.098862,0.009982,0.1,15,75,"{'learning_rate': 0.1, 'max_depth': 15, 'n_est...",0.833768,0.835648,0.834708,0.000940,6
8,440.560269,0.055305,1.049502,0.000247,0.1,15,100,"{'learning_rate': 0.1, 'max_depth': 15, 'n_est...",0.833952,0.835664,0.834808,0.000856,5
2,140.305889,0.483976,0.782338,0.004261,0.1,5,100,"{'learning_rate': 0.1, 'max_depth': 5, 'n_esti...",0.835592,0.837288,0.836440,0.000848,4
3,140.752448,0.172065,0.834867,0.009852,0.1,10,50,"{'learning_rate': 0.1, 'max_depth': 10, 'n_est...",0.836776,0.838160,0.837468,0.000692,3
4,223.660458,0.429166,1.000041,0.002268,0.1,10,75,"{'learning_rate': 0.1, 'max_depth': 10, 'n_est...",0.837200,0.838624,0.837912,0.000712,2
5,296.855083,0.029604,1.022714,0.005326,0.1,10,100,"{'learning_rate': 0.1, 'max_depth': 10, 'n_est...",0.837424,0.839168,0.838296,0.000872,1

In [239]:
# Now try 3-layer MLP
from sklearn.neural_network import MLPClassifier
mlp = MLPClassifier(random_state=1, max_iter=300, hidden_layer_sizes=(100,100,100), verbose=True, early_stopping=True)

In [240]:
clf = mlp.fit(normed_train_data_nophi, train_labels)

Iteration 1, loss = 0.45262418
Validation score: 0.815840

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 2, loss = 0.38986336
Validation score: 0.823400

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 3, loss = 0.38005836
Validation score: 0.824400

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 4, loss = 0.37497854
Validation score: 0.829080

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 5, loss = 0.37272692
Validation score: 0.829680

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 6, loss = 0.37084804
Validation score: 0.830960

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 7, loss = 0.36838506
Validation score: 0.831720

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 8, loss = 0.36761579
Validation score: 0.830120

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 9, loss = 0.36674900
Validation score: 0.831600

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 10, loss = 0.36519213
Validation score: 0.830920

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 11, loss = 0.36425515
Validation score: 0.833560

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 12, loss = 0.36302006
Validation score: 0.833240

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 13, loss = 0.36248385
Validation score: 0.828120

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 14, loss = 0.36124979
Validation score: 0.834200

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 15, loss = 0.36040316
Validation score: 0.833280

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 16, loss = 0.36008271
Validation score: 0.835000

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 17, loss = 0.35950932
Validation score: 0.832880

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 18, loss = 0.35900396
Validation score: 0.832040

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 19, loss = 0.35882802
Validation score: 0.831200

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 20, loss = 0.35822046
Validation score: 0.834560

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 21, loss = 0.35737410
Validation score: 0.835840

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 22, loss = 0.35697600
Validation score: 0.834720

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 23, loss = 0.35640679
Validation score: 0.836000

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 24, loss = 0.35659137
Validation score: 0.835400

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 25, loss = 0.35564804
Validation score: 0.834200

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 26, loss = 0.35559573
Validation score: 0.832600

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 27, loss = 0.35497190
Validation score: 0.834440

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 28, loss = 0.35397931
Validation score: 0.834040

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 29, loss = 0.35394068
Validation score: 0.834680

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 30, loss = 0.35360553
Validation score: 0.834760

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 31, loss = 0.35328588
Validation score: 0.833960

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 32, loss = 0.35294514
Validation score: 0.836560

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 33, loss = 0.35277180
Validation score: 0.835880

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 34, loss = 0.35218526
Validation score: 0.836840

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 35, loss = 0.35216426
Validation score: 0.835200

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 36, loss = 0.35149667
Validation score: 0.835440

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 37, loss = 0.35127105
Validation score: 0.834400

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 38, loss = 0.35126881
Validation score: 0.837360

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 39, loss = 0.35053699
Validation score: 0.835360

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 40, loss = 0.35029626
Validation score: 0.833320

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 41, loss = 0.35041167
Validation score: 0.836360

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 42, loss = 0.34956520
Validation score: 0.838440

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 43, loss = 0.34975451
Validation score: 0.836320

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 44, loss = 0.34965472
Validation score: 0.836920

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 45, loss = 0.34891112
Validation score: 0.835360

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 46, loss = 0.34867539
Validation score: 0.835320

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 47, loss = 0.34838548
Validation score: 0.835760

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 48, loss = 0.34834176
Validation score: 0.834240

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 49, loss = 0.34784310
Validation score: 0.836320

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 50, loss = 0.34763025
Validation score: 0.835280

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 51, loss = 0.34706726
Validation score: 0.835720

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 52, loss = 0.34739166
Validation score: 0.835160

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Iteration 53, loss = 0.34688022
Validation score: 0.837480
Validation score did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

In [245]:
# Training performance
y_pred = clf.predict_proba(normed_train_data_nophi)
y_gold = orig_train_data['Label']
y_weight = orig_train_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y[1] > 0.5:
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TRAINING: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TRAINING: (S,B) = (481.625,27931.434), AMS=2.873, Unweighted Precision = 0.801

In [246]:
y_pred = clf.predict_proba(normed_public_test_data_nophi)
y_gold = orig_public_test_data['Label']
y_weight = orig_public_test_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y[1] > 0.5:
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TRAINING: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TRAINING: (S,B) = (489.301,53626.266), AMS=2.110, Unweighted Precision = 0.634

In [247]:
y_pred = clf.predict_proba(normed_private_test_data_nophi)
y_gold = orig_private_test_data['Label']
y_weight = orig_private_test_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y[1] > 0.5:
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TRAINING: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TRAINING: (S,B) = (327.733,26902.429), AMS=1.994, Unweighted Precision = 0.716

In [249]:
# try more neurons
mlp2 = MLPClassifier(random_state=1, max_iter=300, hidden_layer_sizes=(600,600,600), verbose=True, early_stopping=True)

In [250]:
clf2 = mlp2.fit(normed_train_data_nophi, train_labels)

Iteration 1, loss = 0.42172473

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.817360
Iteration 2, loss = 0.38087185

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.830960
Iteration 3, loss = 0.37539282

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.831760
Iteration 4, loss = 0.37201842

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.829640
Iteration 5, loss = 0.36914945

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.833800
Iteration 6, loss = 0.36809551

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.837600
Iteration 7, loss = 0.36551728

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.835120
Iteration 8, loss = 0.36444930

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.835920
Iteration 9, loss = 0.36391353

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.835800
Iteration 10, loss = 0.36215142

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.836400
Iteration 11, loss = 0.36117579

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.835360
Iteration 12, loss = 0.36009347

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.837160
Iteration 13, loss = 0.35920698

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.829280
Iteration 14, loss = 0.35813793

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.833560
Iteration 15, loss = 0.35750890

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.834960
Iteration 16, loss = 0.35700400

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.831040
Iteration 17, loss = 0.35588359

/Users/nkerstingadxnet.com/anaconda3/lib/python3.8/site-packages/sklearn/base.py:445: UserWarning: X does not have valid feature names, but MLPClassifier was fitted with feature names
  warnings.warn(

Validation score: 0.830760
Validation score did not improve more than tol=0.000100 for 10 consecutive epochs. Stopping.

In [251]:
# Training performance
y_pred = clf2.predict_proba(normed_train_data_nophi)
y_gold = orig_train_data['Label']
y_weight = orig_train_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y[1] > 0.5:
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TRAINING: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TRAINING: (S,B) = (459.674,24264.208), AMS=2.941, Unweighted Precision = 0.805

In [254]:
y_pred = clf2.predict_proba(normed_public_test_data_nophi)
y_gold = orig_public_test_data['Label']
y_weight = orig_public_test_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y[1] > 0.5:
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"VALID: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

VALID: (S,B) = (503.209,51440.257), AMS=2.215, Unweighted Precision = 0.624

In [255]:
y_pred = clf2.predict_proba(normed_private_test_data_nophi)
y_gold = orig_private_test_data['Label']
y_weight = orig_private_test_data['KaggleWeight']
s = 0
b = 0
tp = 0
fp = 0
for i,y in enumerate(y_pred):
    if y[1] > 0.5:
        if y_gold.iloc[i] == 's':
            s += y_weight.iloc[i]
            tp += 1
        else:
            b += y_weight.iloc[i]
            fp += 1
print(f"TESTING: (S,B) = ({s:.3f},{b:.3f}), AMS={AMS(s,b):.3f}, Unweighted Precision = {tp/(tp+fp):.3f}")

TESTING: (S,B) = (383.346,27890.969), AMS=2.290, Unweighted Precision = 0.700